package imagegen

import (
	"fmt"

	"github.com/sqlrush/codexgo/pkg/protocol"
	"github.com/sqlrush/codexgo/pkg/tools"
)

// GeneratedImageOutput is the completed image result returned to the model. Rust:
// GeneratedImageOutput.
type GeneratedImageOutput struct {
	// Result is the base64-encoded PNG bytes returned by the image API.
	Result string
	// OutputHint is the optional persisted-artifact context emitted alongside the
	// image (e.g. the on-disk save path). Nil when absent.
	OutputHint *string
}

// LogPreview avoids copying image bytes into tool-call telemetry. Rust:
// ToolOutput::log_preview.
func (o GeneratedImageOutput) LogPreview() string {
	return "[generated image]"
}

// SuccessForLogging reports a completed images request as successful. Rust:
// ToolOutput::success_for_logging.
func (o GeneratedImageOutput) SuccessForLogging() bool {
	return true
}

// ToResponseItem returns generated bytes and persisted-artifact context for
// model follow-up. Rust: ToolOutput::to_response_item.
func (o GeneratedImageOutput) ToResponseItem(callID string) tools.ResponseInputItem {
	detail := protocol.DefaultImageDetail
	content := []protocol.FunctionCallOutputContentItem{
		{
			Type:     protocol.FunctionCallOutputContentItemKindInputImage,
			ImageURL: fmt.Sprintf("data:image/png;base64,%s", o.Result),
			Detail:   &detail,
		},
	}
	if o.OutputHint != nil {
		content = append(content, protocol.FunctionCallOutputContentItem{
			Type: protocol.FunctionCallOutputContentItemKindInputText,
			Text: *o.OutputHint,
		})
	}
	success := true
	payload := protocol.FunctionCallOutputPayload{
		ContentItems: content,
		Success:      &success,
	}
	return tools.FunctionCallOutputInput(callID, payload)
}
