package tui

// builtInDefaults returns the built-in default keymap.
//
// Port of keymap.rs RuntimeKeymap::built_in_defaults. The default binding lists
// preserve order so the first binding remains the primary UI hint.
func builtInDefaults() RuntimeKeymap {
	return RuntimeKeymap{
		App: AppKeymap{
			OpenTranscript:     KeyBindingList{Ctrl(Char('t'))},
			OpenExternalEditor: KeyBindingList{Ctrl(Char('g'))},
			Copy:               KeyBindingList{Ctrl(Char('o'))},
			ClearTerminal:      KeyBindingList{Ctrl(Char('l'))},
			ToggleVimMode:      KeyBindingList{},
			ToggleFastMode:     KeyBindingList{},
			ToggleRawOutput:    KeyBindingList{Alt(Char('r'))},
		},
		Chat: ChatKeymap{
			InterruptTurn:           KeyBindingList{Plain(KeyEsc)},
			DecreaseReasoningEffort: KeyBindingList{Alt(Char(','))},
			IncreaseReasoningEffort: KeyBindingList{Alt(Char('.'))},
			EditQueuedMessage:       KeyBindingList{Alt(KeyUp), Shift(KeyLeft)},
		},
		Composer: ComposerKeymap{
			Submit:                KeyBindingList{Plain(KeyEnter)},
			Queue:                 KeyBindingList{Plain(KeyTab)},
			ToggleShortcuts:       KeyBindingList{Plain(Char('?')), Shift(Char('?'))},
			HistorySearchPrevious: KeyBindingList{Ctrl(Char('r'))},
			HistorySearchNext:     KeyBindingList{Ctrl(Char('s'))},
		},
		Editor: EditorKeymap{
			InsertNewline: KeyBindingList{
				Ctrl(Char('j')), Ctrl(Char('m')), Plain(KeyEnter),
				Shift(KeyEnter), Alt(KeyEnter),
			},
			MoveLeft:      KeyBindingList{Plain(KeyLeft), Ctrl(Char('b'))},
			MoveRight:     KeyBindingList{Plain(KeyRight), Ctrl(Char('f'))},
			MoveUp:        KeyBindingList{Plain(KeyUp), Ctrl(Char('p'))},
			MoveDown:      KeyBindingList{Plain(KeyDown), Ctrl(Char('n'))},
			MoveWordLeft:  KeyBindingList{Alt(Char('b')), NewKeyBinding(KeyLeft, ModAlt), NewKeyBinding(KeyLeft, ModControl)},
			MoveWordRight: KeyBindingList{Alt(Char('f')), NewKeyBinding(KeyRight, ModAlt), NewKeyBinding(KeyRight, ModControl)},
			MoveLineStart: KeyBindingList{Plain(KeyHome), Ctrl(Char('a'))},
			MoveLineEnd:   KeyBindingList{Plain(KeyEnd), Ctrl(Char('e'))},
			DeleteBackward: KeyBindingList{
				Plain(KeyBackspace), Shift(KeyBackspace), Ctrl(Char('h')),
			},
			DeleteForward: KeyBindingList{
				Plain(KeyDelete), Shift(KeyDelete), Ctrl(Char('d')),
			},
			DeleteBackwardWord: KeyBindingList{
				Alt(KeyBackspace), Ctrl(KeyBackspace),
				NewKeyBinding(KeyBackspace, ModControl|ModShift),
				Ctrl(Char('w')),
				NewKeyBinding(Char('h'), ModControl|ModAlt),
			},
			DeleteForwardWord: KeyBindingList{
				Alt(KeyDelete), Ctrl(KeyDelete),
				NewKeyBinding(KeyDelete, ModControl|ModShift),
				Alt(Char('d')),
			},
			KillLineStart: KeyBindingList{Ctrl(Char('u'))},
			KillWholeLine: KeyBindingList{},
			KillLineEnd:   KeyBindingList{Ctrl(Char('k'))},
			Yank:          KeyBindingList{Ctrl(Char('y'))},
		},
		VimNormal: VimNormalKeymap{
			EnterInsert:         KeyBindingList{Plain(Char('i')), Plain(KeyInsert)},
			AppendAfterCursor:   KeyBindingList{Plain(Char('a'))},
			AppendLineEnd:       KeyBindingList{Shift(Char('a')), Plain(Char('A'))},
			InsertLineStart:     KeyBindingList{Shift(Char('i')), Plain(Char('I'))},
			OpenLineBelow:       KeyBindingList{Plain(Char('o'))},
			OpenLineAbove:       KeyBindingList{Shift(Char('o')), Plain(Char('O'))},
			MoveLeft:            KeyBindingList{Plain(Char('h')), Plain(KeyLeft)},
			MoveRight:           KeyBindingList{Plain(Char('l')), Plain(KeyRight)},
			MoveUp:              KeyBindingList{Plain(Char('k')), Plain(KeyUp)},
			MoveDown:            KeyBindingList{Plain(Char('j')), Plain(KeyDown)},
			MoveWordForward:     KeyBindingList{Plain(Char('w'))},
			MoveWordBackward:    KeyBindingList{Plain(Char('b'))},
			MoveWordEnd:         KeyBindingList{Plain(Char('e'))},
			MoveLineStart:       KeyBindingList{Plain(Char('0'))},
			MoveLineEnd:         KeyBindingList{Plain(Char('$')), Shift(Char('$'))},
			DeleteChar:          KeyBindingList{Plain(Char('x'))},
			SubstituteChar:      KeyBindingList{Plain(Char('s'))},
			DeleteToLineEnd:     KeyBindingList{Shift(Char('d')), Plain(Char('D'))},
			ChangeToLineEnd:     KeyBindingList{Shift(Char('c')), Plain(Char('C'))},
			YankLine:            KeyBindingList{Shift(Char('y')), Plain(Char('Y'))},
			PasteAfter:          KeyBindingList{Plain(Char('p'))},
			StartDeleteOperator: KeyBindingList{Plain(Char('d'))},
			StartYankOperator:   KeyBindingList{Plain(Char('y'))},
			StartChangeOperator: KeyBindingList{Plain(Char('c'))},
			CancelOperator:      KeyBindingList{Plain(KeyEsc)},
		},
		VimOperator: VimOperatorKeymap{
			DeleteLine:             KeyBindingList{Plain(Char('d'))},
			YankLine:               KeyBindingList{Plain(Char('y'))},
			MotionLeft:             KeyBindingList{Plain(Char('h'))},
			MotionRight:            KeyBindingList{Plain(Char('l'))},
			MotionUp:               KeyBindingList{Plain(Char('k'))},
			MotionDown:             KeyBindingList{Plain(Char('j'))},
			MotionWordForward:      KeyBindingList{Plain(Char('w'))},
			MotionWordBackward:     KeyBindingList{Plain(Char('b'))},
			MotionWordEnd:          KeyBindingList{Plain(Char('e'))},
			MotionLineStart:        KeyBindingList{Plain(Char('0'))},
			MotionLineEnd:          KeyBindingList{Plain(Char('$')), Shift(Char('$'))},
			SelectInnerTextObject:  KeyBindingList{Plain(Char('i'))},
			SelectAroundTextObject: KeyBindingList{Plain(Char('a'))},
			Cancel:                 KeyBindingList{Plain(KeyEsc)},
		},
		VimTextObject: VimTextObjectKeymap{
			Word:    KeyBindingList{Plain(Char('w'))},
			BigWord: KeyBindingList{Shift(Char('w')), Plain(Char('W'))},
			Parentheses: KeyBindingList{
				Plain(Char('(')), Shift(Char('(')), Plain(Char(')')),
				Shift(Char(')')), Plain(Char('b')),
			},
			Brackets: KeyBindingList{Plain(Char('[')), Plain(Char(']'))},
			Braces: KeyBindingList{
				Plain(Char('{')), Shift(Char('{')), Plain(Char('}')),
				Shift(Char('}')), Shift(Char('b')), Plain(Char('B')),
			},
			DoubleQuote: KeyBindingList{Plain(Char('"')), Shift(Char('"'))},
			SingleQuote: KeyBindingList{Plain(Char('\''))},
			Backtick:    KeyBindingList{Plain(Char('`'))},
			Cancel:      KeyBindingList{Plain(KeyEsc)},
		},
		Pager: PagerKeymap{
			ScrollUp:        KeyBindingList{Plain(KeyUp), Plain(Char('k'))},
			ScrollDown:      KeyBindingList{Plain(KeyDown), Plain(Char('j'))},
			PageUp:          KeyBindingList{Plain(KeyPageUp), Shift(Char(' ')), Ctrl(Char('b'))},
			PageDown:        KeyBindingList{Plain(KeyPageDown), Plain(Char(' ')), Ctrl(Char('f'))},
			HalfPageUp:      KeyBindingList{Ctrl(Char('u'))},
			HalfPageDown:    KeyBindingList{Ctrl(Char('d'))},
			JumpTop:         KeyBindingList{Plain(KeyHome)},
			JumpBottom:      KeyBindingList{Plain(KeyEnd)},
			Close:           KeyBindingList{Plain(Char('q')), Ctrl(Char('c'))},
			CloseTranscript: KeyBindingList{Ctrl(Char('t'))},
		},
		List: ListKeymap{
			MoveUp:     KeyBindingList{Plain(KeyUp), Ctrl(Char('p')), Ctrl(Char('k')), Plain(Char('k'))},
			MoveDown:   KeyBindingList{Plain(KeyDown), Ctrl(Char('n')), Ctrl(Char('j')), Plain(Char('j'))},
			MoveLeft:   KeyBindingList{Plain(KeyLeft), Ctrl(Char('h'))},
			MoveRight:  KeyBindingList{Plain(KeyRight), Ctrl(Char('l'))},
			PageUp:     KeyBindingList{Plain(KeyPageUp), Ctrl(Char('b'))},
			PageDown:   KeyBindingList{Plain(KeyPageDown), Ctrl(Char('f'))},
			JumpTop:    KeyBindingList{Plain(KeyHome)},
			JumpBottom: KeyBindingList{Plain(KeyEnd)},
			Accept:     KeyBindingList{Plain(KeyEnter)},
			Cancel:     KeyBindingList{Plain(KeyEsc)},
		},
		Approval: ApprovalKeymap{
			OpenFullscreen: KeyBindingList{
				Ctrl(Char('a')),
				NewKeyBinding(Char('a'), ModControl|ModShift),
			},
			OpenThread:        KeyBindingList{Plain(Char('o'))},
			Approve:           KeyBindingList{Plain(Char('y'))},
			ApproveForSession: KeyBindingList{Plain(Char('a'))},
			ApproveForPrefix:  KeyBindingList{Plain(Char('p'))},
			Deny:              KeyBindingList{Plain(Char('d'))},
			Decline:           KeyBindingList{Plain(KeyEsc), Plain(Char('n'))},
			Cancel:            KeyBindingList{Plain(Char('c'))},
		},
	}
}
