package sandbox

import (
	"strings"
	"testing"

	"github.com/sqlrush/codexgo/internal/protocol"
)

// joinSections mirrors how buildSeatbeltPolicy assembles the .sbpl sections so
// golden expectations can be expressed in terms of the embedded assets plus the
// dynamic sections, making the tests robust to verbatim asset updates while still
// asserting byte-for-byte equality of the generated output.
func joinSections(sections ...string) string {
	return strings.Join(sections, "\n")
}

func readEntry(p protocol.FileSystemPath) protocol.FileSystemSandboxEntry {
	return protocol.FileSystemSandboxEntry{Path: p, Access: protocol.FileSystemAccessModeRead}
}

func writeEntry(p protocol.FileSystemPath) protocol.FileSystemSandboxEntry {
	return protocol.FileSystemSandboxEntry{Path: p, Access: protocol.FileSystemAccessModeWrite}
}

func denyEntry(p protocol.FileSystemPath) protocol.FileSystemSandboxEntry {
	return protocol.FileSystemSandboxEntry{Path: p, Access: protocol.FileSystemAccessModeDeny}
}

func specialRoot() protocol.FileSystemPath {
	return protocol.NewFileSystemSpecialPath(protocol.FileSystemSpecialPath{Kind: protocol.FileSystemSpecialPathKindRoot})
}

func absPath(p string) protocol.FileSystemPath {
	return protocol.NewFileSystemPath(protocol.AbsolutePath(p))
}

func restrictedPolicy(entries ...protocol.FileSystemSandboxEntry) protocol.FileSystemSandboxPolicy {
	return protocol.FileSystemSandboxPolicy{Kind: protocol.FileSystemSandboxKindRestricted, Entries: entries}
}

// TestBuildSeatbeltPolicyGoldenReadOnly asserts the full-disk read-only policy is
// generated byte-for-byte: base asset, the full read allow, then empty
// write/deny/network sections joined with newlines.
func TestBuildSeatbeltPolicyGoldenReadOnly(t *testing.T) {
	t.Parallel()
	fs := restrictedPolicy(readEntry(specialRoot()))

	policy, params := buildSeatbeltPolicy(CreateSeatbeltCommandArgsParams{
		Command:                 []string{"/bin/true"},
		FileSystemSandboxPolicy: fs,
		NetworkSandboxPolicy:    protocol.NetworkSandboxPolicyRestricted,
		SandboxPolicyCwd:        "/",
	})

	want := joinSections(
		macosSeatbeltBasePolicy,
		"; allow read-only file operations\n(allow file-read*)",
		"", // file-write
		"", // deny-read
		"", // network
	)
	if policy != want {
		t.Fatalf("read-only policy mismatch:\n--- got ---\n%s\n--- want ---\n%s", policy, want)
	}
	if len(params) != 0 {
		t.Fatalf("expected no -D params, got %#v", params)
	}
}

// TestBuildSeatbeltPolicyGoldenFullNetwork asserts the full-network section is
// appended verbatim (network-outbound/inbound allow + the network asset).
func TestBuildSeatbeltPolicyGoldenFullNetwork(t *testing.T) {
	t.Parallel()
	fs := restrictedPolicy(readEntry(specialRoot()))

	policy, _ := buildSeatbeltPolicy(CreateSeatbeltCommandArgsParams{
		Command:                 []string{"/bin/true"},
		FileSystemSandboxPolicy: fs,
		NetworkSandboxPolicy:    protocol.NetworkSandboxPolicyEnabled,
		SandboxPolicyCwd:        "/",
	})

	wantNetwork := "(allow network-outbound)\n(allow network-inbound)\n" + macosSeatbeltNetworkPolicy
	want := joinSections(
		macosSeatbeltBasePolicy,
		"; allow read-only file operations\n(allow file-read*)",
		"",
		"",
		wantNetwork,
	)
	if policy != want {
		t.Fatalf("full-network policy mismatch:\n--- got ---\n%s\n--- want ---\n%s", policy, want)
	}
}

// TestBuildSeatbeltPolicyGoldenWritableRootWithProtectedMetadata asserts a
// writable root carries the protected-metadata require-not regexes and the
// matching -D params, byte-for-byte. The root has no .git/.agents/.codexgo on disk
// so there are no excluded subpaths, only metadata-name regexes.
func TestBuildSeatbeltPolicyGoldenWritableRootWithProtectedMetadata(t *testing.T) {
	t.Parallel()
	root := t.TempDir()
	resolved, ok := normalizePathForSandbox(root)
	if !ok {
		t.Fatalf("normalize temp root %q failed", root)
	}
	// Use a distinct cwd so the writable root is not the workspace root; this
	// avoids forcing a missing .codexgo into the excluded subpaths and keeps the
	// write section limited to the protected-metadata regexes.
	cwd, ok := normalizePathForSandbox(t.TempDir())
	if !ok {
		t.Fatalf("normalize temp cwd failed")
	}

	fs := restrictedPolicy(
		readEntry(specialRoot()),
		writeEntry(absPath(resolved)),
	)

	policy, params := buildSeatbeltPolicy(CreateSeatbeltCommandArgsParams{
		Command:                 []string{"/bin/true"},
		FileSystemSandboxPolicy: fs,
		NetworkSandboxPolicy:    protocol.NetworkSandboxPolicyRestricted,
		SandboxPolicyCwd:        cwd,
	})

	// Protected metadata regexes appear in writable-root order: .git, .agents, .codexgo.
	requireParts := []string{`(subpath (param "WRITABLE_ROOT_0"))`}
	for _, name := range protectedMetadataPathNames {
		regex := strings.ReplaceAll(seatbeltProtectedMetadataNameRegex(resolved, name), `"`, `\"`)
		requireParts = append(requireParts, `(require-not (regex #"`+regex+`"))`)
	}
	wantWrite := "(allow file-write*\n(require-all " + strings.Join(requireParts, " ") + " )\n)"

	want := joinSections(
		macosSeatbeltBasePolicy,
		"; allow read-only file operations\n(allow file-read*)",
		wantWrite,
		"",
		"",
	)
	if policy != want {
		t.Fatalf("writable-root policy mismatch:\n--- got ---\n%s\n--- want ---\n%s", policy, want)
	}

	if len(params) != 1 || params[0].key != "WRITABLE_ROOT_0" || params[0].path != resolved {
		t.Fatalf("expected single WRITABLE_ROOT_0=%s param, got %#v", resolved, params)
	}
}

// TestBuildSeatbeltPolicyGoldenFullDiskWriteWithUnreadableCarveout asserts that a
// Special(Root)-write policy with an explicit deny generates the full-disk write
// over "/" with literal+subpath require-not carveouts and the metadata regexes,
// plus the matching -D params (matching the Rust
// explicit_unreadable_paths_are_excluded_from_full_disk_read_and_write_access
// expectations).
func TestBuildSeatbeltPolicyGoldenFullDiskWriteWithUnreadableCarveout(t *testing.T) {
	t.Parallel()
	unreadable := "/tmp/codex-unreadable"
	fs := restrictedPolicy(
		writeEntry(specialRoot()),
		denyEntry(absPath(unreadable)),
	)

	_, params := buildSeatbeltPolicy(CreateSeatbeltCommandArgsParams{
		Command:                 []string{"/bin/true"},
		FileSystemSandboxPolicy: fs,
		NetworkSandboxPolicy:    protocol.NetworkSandboxPolicyRestricted,
		SandboxPolicyCwd:        "/",
	})

	// The writable definitions must match codex exactly.
	var writableDefs []dirParam
	for _, p := range params {
		if strings.HasPrefix(p.key, "WRITABLE_ROOT") {
			writableDefs = append(writableDefs, p)
		}
	}
	want := []dirParam{
		{key: "WRITABLE_ROOT_0", path: "/"},
		{key: "WRITABLE_ROOT_0_EXCLUDED_0", path: "/.codexgo"},
		{key: "WRITABLE_ROOT_0_EXCLUDED_1", path: unreadable},
	}
	if len(writableDefs) != len(want) {
		t.Fatalf("writable defs = %#v, want %#v", writableDefs, want)
	}
	for i := range want {
		if writableDefs[i] != want[i] {
			t.Fatalf("writable def[%d] = %#v, want %#v", i, writableDefs[i], want[i])
		}
	}
}
