package cli

// Code generated from `codex completion bash` (clap_complete v4.5.65) — DO NOT EDIT.
// This file embeds the codex command tree (subcommand nesting, per-node option
// lists, COMP_CWORD levels, and per-flag value hints) extracted byte-for-byte
// from the reference binary's bash completion output. The shell generators
// (completion_bash.go, completion_zsh.go, completion_fish.go) render from this
// data plus the richer zsh/fish metadata embedded alongside their generators.

// bashSubcmdEntry is one arm of the bash for-loop command dispatch:
// `case "${cmd},${i}"` maps (Parent, Name) to the resolved Fn node id.
type bashSubcmdEntry struct {
	Parent string
	Name   string
	Fn     string
}

var bashSubcmdMap = []bashSubcmdEntry{
	{Parent: "codex", Name: "a", Fn: "codex__apply"},
	{Parent: "codex", Name: "app", Fn: "codex__app"},
	{Parent: "codex", Name: "app-server", Fn: "codex__app__server"},
	{Parent: "codex", Name: "apply", Fn: "codex__apply"},
	{Parent: "codex", Name: "archive", Fn: "codex__archive"},
	{Parent: "codex", Name: "cloud", Fn: "codex__cloud"},
	{Parent: "codex", Name: "completion", Fn: "codex__completion"},
	{Parent: "codex", Name: "debug", Fn: "codex__debug"},
	{Parent: "codex", Name: "doctor", Fn: "codex__doctor"},
	{Parent: "codex", Name: "e", Fn: "codex__exec"},
	{Parent: "codex", Name: "exec", Fn: "codex__exec"},
	{Parent: "codex", Name: "exec-server", Fn: "codex__exec__server"},
	{Parent: "codex", Name: "execpolicy", Fn: "codex__execpolicy"},
	{Parent: "codex", Name: "features", Fn: "codex__features"},
	{Parent: "codex", Name: "fork", Fn: "codex__fork"},
	{Parent: "codex", Name: "help", Fn: "codex__help"},
	{Parent: "codex", Name: "login", Fn: "codex__login"},
	{Parent: "codex", Name: "logout", Fn: "codex__logout"},
	{Parent: "codex", Name: "mcp", Fn: "codex__mcp"},
	{Parent: "codex", Name: "mcp-server", Fn: "codex__mcp__server"},
	{Parent: "codex", Name: "plugin", Fn: "codex__plugin"},
	{Parent: "codex", Name: "remote-control", Fn: "codex__remote__control"},
	{Parent: "codex", Name: "responses-api-proxy", Fn: "codex__responses__api__proxy"},
	{Parent: "codex", Name: "resume", Fn: "codex__resume"},
	{Parent: "codex", Name: "review", Fn: "codex__review"},
	{Parent: "codex", Name: "sandbox", Fn: "codex__sandbox"},
	{Parent: "codex", Name: "stdio-to-uds", Fn: "codex__stdio__to__uds"},
	{Parent: "codex", Name: "unarchive", Fn: "codex__unarchive"},
	{Parent: "codex", Name: "update", Fn: "codex__update"},
	{Parent: "codex__app__server", Name: "daemon", Fn: "codex__app__server__daemon"},
	{Parent: "codex__app__server", Name: "generate-internal-json-schema", Fn: "codex__app__server__generate__internal__json__schema"},
	{Parent: "codex__app__server", Name: "generate-json-schema", Fn: "codex__app__server__generate__json__schema"},
	{Parent: "codex__app__server", Name: "generate-ts", Fn: "codex__app__server__generate__ts"},
	{Parent: "codex__app__server", Name: "help", Fn: "codex__app__server__help"},
	{Parent: "codex__app__server", Name: "proxy", Fn: "codex__app__server__proxy"},
	{Parent: "codex__app__server__daemon", Name: "bootstrap", Fn: "codex__app__server__daemon__bootstrap"},
	{Parent: "codex__app__server__daemon", Name: "disable-remote-control", Fn: "codex__app__server__daemon__disable__remote__control"},
	{Parent: "codex__app__server__daemon", Name: "enable-remote-control", Fn: "codex__app__server__daemon__enable__remote__control"},
	{Parent: "codex__app__server__daemon", Name: "help", Fn: "codex__app__server__daemon__help"},
	{Parent: "codex__app__server__daemon", Name: "pid-update-loop", Fn: "codex__app__server__daemon__pid__update__loop"},
	{Parent: "codex__app__server__daemon", Name: "restart", Fn: "codex__app__server__daemon__restart"},
	{Parent: "codex__app__server__daemon", Name: "start", Fn: "codex__app__server__daemon__start"},
	{Parent: "codex__app__server__daemon", Name: "stop", Fn: "codex__app__server__daemon__stop"},
	{Parent: "codex__app__server__daemon", Name: "version", Fn: "codex__app__server__daemon__version"},
	{Parent: "codex__app__server__daemon__help", Name: "bootstrap", Fn: "codex__app__server__daemon__help__bootstrap"},
	{Parent: "codex__app__server__daemon__help", Name: "disable-remote-control", Fn: "codex__app__server__daemon__help__disable__remote__control"},
	{Parent: "codex__app__server__daemon__help", Name: "enable-remote-control", Fn: "codex__app__server__daemon__help__enable__remote__control"},
	{Parent: "codex__app__server__daemon__help", Name: "help", Fn: "codex__app__server__daemon__help__help"},
	{Parent: "codex__app__server__daemon__help", Name: "pid-update-loop", Fn: "codex__app__server__daemon__help__pid__update__loop"},
	{Parent: "codex__app__server__daemon__help", Name: "restart", Fn: "codex__app__server__daemon__help__restart"},
	{Parent: "codex__app__server__daemon__help", Name: "start", Fn: "codex__app__server__daemon__help__start"},
	{Parent: "codex__app__server__daemon__help", Name: "stop", Fn: "codex__app__server__daemon__help__stop"},
	{Parent: "codex__app__server__daemon__help", Name: "version", Fn: "codex__app__server__daemon__help__version"},
	{Parent: "codex__app__server__help", Name: "daemon", Fn: "codex__app__server__help__daemon"},
	{Parent: "codex__app__server__help", Name: "generate-internal-json-schema", Fn: "codex__app__server__help__generate__internal__json__schema"},
	{Parent: "codex__app__server__help", Name: "generate-json-schema", Fn: "codex__app__server__help__generate__json__schema"},
	{Parent: "codex__app__server__help", Name: "generate-ts", Fn: "codex__app__server__help__generate__ts"},
	{Parent: "codex__app__server__help", Name: "help", Fn: "codex__app__server__help__help"},
	{Parent: "codex__app__server__help", Name: "proxy", Fn: "codex__app__server__help__proxy"},
	{Parent: "codex__app__server__help__daemon", Name: "bootstrap", Fn: "codex__app__server__help__daemon__bootstrap"},
	{Parent: "codex__app__server__help__daemon", Name: "disable-remote-control", Fn: "codex__app__server__help__daemon__disable__remote__control"},
	{Parent: "codex__app__server__help__daemon", Name: "enable-remote-control", Fn: "codex__app__server__help__daemon__enable__remote__control"},
	{Parent: "codex__app__server__help__daemon", Name: "pid-update-loop", Fn: "codex__app__server__help__daemon__pid__update__loop"},
	{Parent: "codex__app__server__help__daemon", Name: "restart", Fn: "codex__app__server__help__daemon__restart"},
	{Parent: "codex__app__server__help__daemon", Name: "start", Fn: "codex__app__server__help__daemon__start"},
	{Parent: "codex__app__server__help__daemon", Name: "stop", Fn: "codex__app__server__help__daemon__stop"},
	{Parent: "codex__app__server__help__daemon", Name: "version", Fn: "codex__app__server__help__daemon__version"},
	{Parent: "codex__cloud", Name: "apply", Fn: "codex__cloud__apply"},
	{Parent: "codex__cloud", Name: "diff", Fn: "codex__cloud__diff"},
	{Parent: "codex__cloud", Name: "exec", Fn: "codex__cloud__exec"},
	{Parent: "codex__cloud", Name: "help", Fn: "codex__cloud__help"},
	{Parent: "codex__cloud", Name: "list", Fn: "codex__cloud__list"},
	{Parent: "codex__cloud", Name: "status", Fn: "codex__cloud__status"},
	{Parent: "codex__cloud__help", Name: "apply", Fn: "codex__cloud__help__apply"},
	{Parent: "codex__cloud__help", Name: "diff", Fn: "codex__cloud__help__diff"},
	{Parent: "codex__cloud__help", Name: "exec", Fn: "codex__cloud__help__exec"},
	{Parent: "codex__cloud__help", Name: "help", Fn: "codex__cloud__help__help"},
	{Parent: "codex__cloud__help", Name: "list", Fn: "codex__cloud__help__list"},
	{Parent: "codex__cloud__help", Name: "status", Fn: "codex__cloud__help__status"},
	{Parent: "codex__debug", Name: "app-server", Fn: "codex__debug__app__server"},
	{Parent: "codex__debug", Name: "clear-memories", Fn: "codex__debug__clear__memories"},
	{Parent: "codex__debug", Name: "help", Fn: "codex__debug__help"},
	{Parent: "codex__debug", Name: "models", Fn: "codex__debug__models"},
	{Parent: "codex__debug", Name: "prompt-input", Fn: "codex__debug__prompt__input"},
	{Parent: "codex__debug", Name: "trace-reduce", Fn: "codex__debug__trace__reduce"},
	{Parent: "codex__debug__app__server", Name: "help", Fn: "codex__debug__app__server__help"},
	{Parent: "codex__debug__app__server", Name: "send-message-v2", Fn: "codex__debug__app__server__send__message__v2"},
	{Parent: "codex__debug__app__server__help", Name: "help", Fn: "codex__debug__app__server__help__help"},
	{Parent: "codex__debug__app__server__help", Name: "send-message-v2", Fn: "codex__debug__app__server__help__send__message__v2"},
	{Parent: "codex__debug__help", Name: "app-server", Fn: "codex__debug__help__app__server"},
	{Parent: "codex__debug__help", Name: "clear-memories", Fn: "codex__debug__help__clear__memories"},
	{Parent: "codex__debug__help", Name: "help", Fn: "codex__debug__help__help"},
	{Parent: "codex__debug__help", Name: "models", Fn: "codex__debug__help__models"},
	{Parent: "codex__debug__help", Name: "prompt-input", Fn: "codex__debug__help__prompt__input"},
	{Parent: "codex__debug__help", Name: "trace-reduce", Fn: "codex__debug__help__trace__reduce"},
	{Parent: "codex__debug__help__app__server", Name: "send-message-v2", Fn: "codex__debug__help__app__server__send__message__v2"},
	{Parent: "codex__exec", Name: "help", Fn: "codex__exec__help"},
	{Parent: "codex__exec", Name: "resume", Fn: "codex__exec__resume"},
	{Parent: "codex__exec", Name: "review", Fn: "codex__exec__review"},
	{Parent: "codex__exec__help", Name: "help", Fn: "codex__exec__help__help"},
	{Parent: "codex__exec__help", Name: "resume", Fn: "codex__exec__help__resume"},
	{Parent: "codex__exec__help", Name: "review", Fn: "codex__exec__help__review"},
	{Parent: "codex__execpolicy", Name: "check", Fn: "codex__execpolicy__check"},
	{Parent: "codex__execpolicy", Name: "help", Fn: "codex__execpolicy__help"},
	{Parent: "codex__execpolicy__help", Name: "check", Fn: "codex__execpolicy__help__check"},
	{Parent: "codex__execpolicy__help", Name: "help", Fn: "codex__execpolicy__help__help"},
	{Parent: "codex__features", Name: "disable", Fn: "codex__features__disable"},
	{Parent: "codex__features", Name: "enable", Fn: "codex__features__enable"},
	{Parent: "codex__features", Name: "help", Fn: "codex__features__help"},
	{Parent: "codex__features", Name: "list", Fn: "codex__features__list"},
	{Parent: "codex__features__help", Name: "disable", Fn: "codex__features__help__disable"},
	{Parent: "codex__features__help", Name: "enable", Fn: "codex__features__help__enable"},
	{Parent: "codex__features__help", Name: "help", Fn: "codex__features__help__help"},
	{Parent: "codex__features__help", Name: "list", Fn: "codex__features__help__list"},
	{Parent: "codex__help", Name: "app", Fn: "codex__help__app"},
	{Parent: "codex__help", Name: "app-server", Fn: "codex__help__app__server"},
	{Parent: "codex__help", Name: "apply", Fn: "codex__help__apply"},
	{Parent: "codex__help", Name: "archive", Fn: "codex__help__archive"},
	{Parent: "codex__help", Name: "cloud", Fn: "codex__help__cloud"},
	{Parent: "codex__help", Name: "completion", Fn: "codex__help__completion"},
	{Parent: "codex__help", Name: "debug", Fn: "codex__help__debug"},
	{Parent: "codex__help", Name: "doctor", Fn: "codex__help__doctor"},
	{Parent: "codex__help", Name: "exec", Fn: "codex__help__exec"},
	{Parent: "codex__help", Name: "exec-server", Fn: "codex__help__exec__server"},
	{Parent: "codex__help", Name: "execpolicy", Fn: "codex__help__execpolicy"},
	{Parent: "codex__help", Name: "features", Fn: "codex__help__features"},
	{Parent: "codex__help", Name: "fork", Fn: "codex__help__fork"},
	{Parent: "codex__help", Name: "help", Fn: "codex__help__help"},
	{Parent: "codex__help", Name: "login", Fn: "codex__help__login"},
	{Parent: "codex__help", Name: "logout", Fn: "codex__help__logout"},
	{Parent: "codex__help", Name: "mcp", Fn: "codex__help__mcp"},
	{Parent: "codex__help", Name: "mcp-server", Fn: "codex__help__mcp__server"},
	{Parent: "codex__help", Name: "plugin", Fn: "codex__help__plugin"},
	{Parent: "codex__help", Name: "remote-control", Fn: "codex__help__remote__control"},
	{Parent: "codex__help", Name: "responses-api-proxy", Fn: "codex__help__responses__api__proxy"},
	{Parent: "codex__help", Name: "resume", Fn: "codex__help__resume"},
	{Parent: "codex__help", Name: "review", Fn: "codex__help__review"},
	{Parent: "codex__help", Name: "sandbox", Fn: "codex__help__sandbox"},
	{Parent: "codex__help", Name: "stdio-to-uds", Fn: "codex__help__stdio__to__uds"},
	{Parent: "codex__help", Name: "unarchive", Fn: "codex__help__unarchive"},
	{Parent: "codex__help", Name: "update", Fn: "codex__help__update"},
	{Parent: "codex__help__app__server", Name: "daemon", Fn: "codex__help__app__server__daemon"},
	{Parent: "codex__help__app__server", Name: "generate-internal-json-schema", Fn: "codex__help__app__server__generate__internal__json__schema"},
	{Parent: "codex__help__app__server", Name: "generate-json-schema", Fn: "codex__help__app__server__generate__json__schema"},
	{Parent: "codex__help__app__server", Name: "generate-ts", Fn: "codex__help__app__server__generate__ts"},
	{Parent: "codex__help__app__server", Name: "proxy", Fn: "codex__help__app__server__proxy"},
	{Parent: "codex__help__app__server__daemon", Name: "bootstrap", Fn: "codex__help__app__server__daemon__bootstrap"},
	{Parent: "codex__help__app__server__daemon", Name: "disable-remote-control", Fn: "codex__help__app__server__daemon__disable__remote__control"},
	{Parent: "codex__help__app__server__daemon", Name: "enable-remote-control", Fn: "codex__help__app__server__daemon__enable__remote__control"},
	{Parent: "codex__help__app__server__daemon", Name: "pid-update-loop", Fn: "codex__help__app__server__daemon__pid__update__loop"},
	{Parent: "codex__help__app__server__daemon", Name: "restart", Fn: "codex__help__app__server__daemon__restart"},
	{Parent: "codex__help__app__server__daemon", Name: "start", Fn: "codex__help__app__server__daemon__start"},
	{Parent: "codex__help__app__server__daemon", Name: "stop", Fn: "codex__help__app__server__daemon__stop"},
	{Parent: "codex__help__app__server__daemon", Name: "version", Fn: "codex__help__app__server__daemon__version"},
	{Parent: "codex__help__cloud", Name: "apply", Fn: "codex__help__cloud__apply"},
	{Parent: "codex__help__cloud", Name: "diff", Fn: "codex__help__cloud__diff"},
	{Parent: "codex__help__cloud", Name: "exec", Fn: "codex__help__cloud__exec"},
	{Parent: "codex__help__cloud", Name: "list", Fn: "codex__help__cloud__list"},
	{Parent: "codex__help__cloud", Name: "status", Fn: "codex__help__cloud__status"},
	{Parent: "codex__help__debug", Name: "app-server", Fn: "codex__help__debug__app__server"},
	{Parent: "codex__help__debug", Name: "clear-memories", Fn: "codex__help__debug__clear__memories"},
	{Parent: "codex__help__debug", Name: "models", Fn: "codex__help__debug__models"},
	{Parent: "codex__help__debug", Name: "prompt-input", Fn: "codex__help__debug__prompt__input"},
	{Parent: "codex__help__debug", Name: "trace-reduce", Fn: "codex__help__debug__trace__reduce"},
	{Parent: "codex__help__debug__app__server", Name: "send-message-v2", Fn: "codex__help__debug__app__server__send__message__v2"},
	{Parent: "codex__help__exec", Name: "resume", Fn: "codex__help__exec__resume"},
	{Parent: "codex__help__exec", Name: "review", Fn: "codex__help__exec__review"},
	{Parent: "codex__help__execpolicy", Name: "check", Fn: "codex__help__execpolicy__check"},
	{Parent: "codex__help__features", Name: "disable", Fn: "codex__help__features__disable"},
	{Parent: "codex__help__features", Name: "enable", Fn: "codex__help__features__enable"},
	{Parent: "codex__help__features", Name: "list", Fn: "codex__help__features__list"},
	{Parent: "codex__help__login", Name: "status", Fn: "codex__help__login__status"},
	{Parent: "codex__help__mcp", Name: "add", Fn: "codex__help__mcp__add"},
	{Parent: "codex__help__mcp", Name: "get", Fn: "codex__help__mcp__get"},
	{Parent: "codex__help__mcp", Name: "list", Fn: "codex__help__mcp__list"},
	{Parent: "codex__help__mcp", Name: "login", Fn: "codex__help__mcp__login"},
	{Parent: "codex__help__mcp", Name: "logout", Fn: "codex__help__mcp__logout"},
	{Parent: "codex__help__mcp", Name: "remove", Fn: "codex__help__mcp__remove"},
	{Parent: "codex__help__plugin", Name: "add", Fn: "codex__help__plugin__add"},
	{Parent: "codex__help__plugin", Name: "list", Fn: "codex__help__plugin__list"},
	{Parent: "codex__help__plugin", Name: "marketplace", Fn: "codex__help__plugin__marketplace"},
	{Parent: "codex__help__plugin", Name: "remove", Fn: "codex__help__plugin__remove"},
	{Parent: "codex__help__plugin__marketplace", Name: "add", Fn: "codex__help__plugin__marketplace__add"},
	{Parent: "codex__help__plugin__marketplace", Name: "list", Fn: "codex__help__plugin__marketplace__list"},
	{Parent: "codex__help__plugin__marketplace", Name: "remove", Fn: "codex__help__plugin__marketplace__remove"},
	{Parent: "codex__help__plugin__marketplace", Name: "upgrade", Fn: "codex__help__plugin__marketplace__upgrade"},
	{Parent: "codex__help__remote__control", Name: "start", Fn: "codex__help__remote__control__start"},
	{Parent: "codex__help__remote__control", Name: "stop", Fn: "codex__help__remote__control__stop"},
	{Parent: "codex__login", Name: "help", Fn: "codex__login__help"},
	{Parent: "codex__login", Name: "status", Fn: "codex__login__status"},
	{Parent: "codex__login__help", Name: "help", Fn: "codex__login__help__help"},
	{Parent: "codex__login__help", Name: "status", Fn: "codex__login__help__status"},
	{Parent: "codex__mcp", Name: "add", Fn: "codex__mcp__add"},
	{Parent: "codex__mcp", Name: "get", Fn: "codex__mcp__get"},
	{Parent: "codex__mcp", Name: "help", Fn: "codex__mcp__help"},
	{Parent: "codex__mcp", Name: "list", Fn: "codex__mcp__list"},
	{Parent: "codex__mcp", Name: "login", Fn: "codex__mcp__login"},
	{Parent: "codex__mcp", Name: "logout", Fn: "codex__mcp__logout"},
	{Parent: "codex__mcp", Name: "remove", Fn: "codex__mcp__remove"},
	{Parent: "codex__mcp__help", Name: "add", Fn: "codex__mcp__help__add"},
	{Parent: "codex__mcp__help", Name: "get", Fn: "codex__mcp__help__get"},
	{Parent: "codex__mcp__help", Name: "help", Fn: "codex__mcp__help__help"},
	{Parent: "codex__mcp__help", Name: "list", Fn: "codex__mcp__help__list"},
	{Parent: "codex__mcp__help", Name: "login", Fn: "codex__mcp__help__login"},
	{Parent: "codex__mcp__help", Name: "logout", Fn: "codex__mcp__help__logout"},
	{Parent: "codex__mcp__help", Name: "remove", Fn: "codex__mcp__help__remove"},
	{Parent: "codex__plugin", Name: "add", Fn: "codex__plugin__add"},
	{Parent: "codex__plugin", Name: "help", Fn: "codex__plugin__help"},
	{Parent: "codex__plugin", Name: "list", Fn: "codex__plugin__list"},
	{Parent: "codex__plugin", Name: "marketplace", Fn: "codex__plugin__marketplace"},
	{Parent: "codex__plugin", Name: "remove", Fn: "codex__plugin__remove"},
	{Parent: "codex__plugin__help", Name: "add", Fn: "codex__plugin__help__add"},
	{Parent: "codex__plugin__help", Name: "help", Fn: "codex__plugin__help__help"},
	{Parent: "codex__plugin__help", Name: "list", Fn: "codex__plugin__help__list"},
	{Parent: "codex__plugin__help", Name: "marketplace", Fn: "codex__plugin__help__marketplace"},
	{Parent: "codex__plugin__help", Name: "remove", Fn: "codex__plugin__help__remove"},
	{Parent: "codex__plugin__help__marketplace", Name: "add", Fn: "codex__plugin__help__marketplace__add"},
	{Parent: "codex__plugin__help__marketplace", Name: "list", Fn: "codex__plugin__help__marketplace__list"},
	{Parent: "codex__plugin__help__marketplace", Name: "remove", Fn: "codex__plugin__help__marketplace__remove"},
	{Parent: "codex__plugin__help__marketplace", Name: "upgrade", Fn: "codex__plugin__help__marketplace__upgrade"},
	{Parent: "codex__plugin__marketplace", Name: "add", Fn: "codex__plugin__marketplace__add"},
	{Parent: "codex__plugin__marketplace", Name: "help", Fn: "codex__plugin__marketplace__help"},
	{Parent: "codex__plugin__marketplace", Name: "list", Fn: "codex__plugin__marketplace__list"},
	{Parent: "codex__plugin__marketplace", Name: "remove", Fn: "codex__plugin__marketplace__remove"},
	{Parent: "codex__plugin__marketplace", Name: "upgrade", Fn: "codex__plugin__marketplace__upgrade"},
	{Parent: "codex__plugin__marketplace__help", Name: "add", Fn: "codex__plugin__marketplace__help__add"},
	{Parent: "codex__plugin__marketplace__help", Name: "help", Fn: "codex__plugin__marketplace__help__help"},
	{Parent: "codex__plugin__marketplace__help", Name: "list", Fn: "codex__plugin__marketplace__help__list"},
	{Parent: "codex__plugin__marketplace__help", Name: "remove", Fn: "codex__plugin__marketplace__help__remove"},
	{Parent: "codex__plugin__marketplace__help", Name: "upgrade", Fn: "codex__plugin__marketplace__help__upgrade"},
	{Parent: "codex__remote__control", Name: "help", Fn: "codex__remote__control__help"},
	{Parent: "codex__remote__control", Name: "start", Fn: "codex__remote__control__start"},
	{Parent: "codex__remote__control", Name: "stop", Fn: "codex__remote__control__stop"},
	{Parent: "codex__remote__control__help", Name: "help", Fn: "codex__remote__control__help__help"},
	{Parent: "codex__remote__control__help", Name: "start", Fn: "codex__remote__control__help__start"},
	{Parent: "codex__remote__control__help", Name: "stop", Fn: "codex__remote__control__help__stop"},
}

// bashFlagDetail is one `case "${prev}"` arm: Flag plus its value-hint Kind
// ("file" -> compgen -f, "dir" -> plusdirs, "vals" -> compgen -W with Vals).
type bashFlagDetail struct {
	Flag string
	Kind string
	Vals string
}

// completionNode is one node of the codex command tree: Fn is the bash
// case label (e.g. codex__cloud), Opts is the space-joined option/positional/
// subcommand list, Level is the COMP_CWORD depth, and Flags holds prev-arm hints.
type completionNode struct {
	Fn    string
	Opts  string
	Level int
	Flags []bashFlagDetail
}

// completionTree lists every command-tree node in clap declaration order
// (the order the bash subcmd_details arms appear). Index 0 is the root `codex`.
var completionTree = []completionNode{
	{Fn: "codex", Opts: "-c -i -m -p -s -C -a -h -V --config --enable --disable --remote --remote-auth-token-env --strict-config --image --model --oss --local-provider --profile --sandbox --dangerously-bypass-hook-trust --cd --add-dir --dangerously-bypass-approvals-and-sandbox --ask-for-approval --search --no-alt-screen --help --version [PROMPT] exec e review login logout mcp plugin mcp-server app-server remote-control app completion update doctor sandbox debug execpolicy apply a resume archive unarchive fork cloud responses-api-proxy stdio-to-uds exec-server features help", Level: 1, Flags: []bashFlagDetail{
		{Flag: "--config", Kind: "file", Vals: ""},
		{Flag: "-c", Kind: "file", Vals: ""},
		{Flag: "--enable", Kind: "file", Vals: ""},
		{Flag: "--disable", Kind: "file", Vals: ""},
		{Flag: "--remote", Kind: "file", Vals: ""},
		{Flag: "--remote-auth-token-env", Kind: "file", Vals: ""},
		{Flag: "--image", Kind: "file", Vals: ""},
		{Flag: "-i", Kind: "file", Vals: ""},
		{Flag: "--model", Kind: "file", Vals: ""},
		{Flag: "-m", Kind: "file", Vals: ""},
		{Flag: "--local-provider", Kind: "file", Vals: ""},
		{Flag: "--profile", Kind: "file", Vals: ""},
		{Flag: "-p", Kind: "file", Vals: ""},
		{Flag: "--sandbox", Kind: "vals", Vals: "read-only workspace-write danger-full-access"},
		{Flag: "-s", Kind: "vals", Vals: "read-only workspace-write danger-full-access"},
		{Flag: "--cd", Kind: "file", Vals: ""},
		{Flag: "-C", Kind: "file", Vals: ""},
		{Flag: "--add-dir", Kind: "dir", Vals: ""},
		{Flag: "--ask-for-approval", Kind: "vals", Vals: "untrusted on-failure on-request never"},
		{Flag: "-a", Kind: "vals", Vals: "untrusted on-failure on-request never"},
	}},
	{Fn: "codex__app", Opts: "-c -h --download-url --config --enable --disable --help [PATH]", Level: 2, Flags: []bashFlagDetail{
		{Flag: "--download-url", Kind: "file", Vals: ""},
		{Flag: "--config", Kind: "file", Vals: ""},
		{Flag: "-c", Kind: "file", Vals: ""},
		{Flag: "--enable", Kind: "file", Vals: ""},
		{Flag: "--disable", Kind: "file", Vals: ""},
	}},
	{Fn: "codex__app__server", Opts: "-c -h --strict-config --listen --stdio --remote-control --analytics-default-enabled --ws-auth --ws-token-file --ws-token-sha256 --ws-shared-secret-file --ws-issuer --ws-audience --ws-max-clock-skew-seconds --config --enable --disable --help daemon proxy generate-ts generate-json-schema generate-internal-json-schema help", Level: 2, Flags: []bashFlagDetail{
		{Flag: "--listen", Kind: "file", Vals: ""},
		{Flag: "--ws-auth", Kind: "vals", Vals: "capability-token signed-bearer-token"},
		{Flag: "--ws-token-file", Kind: "file", Vals: ""},
		{Flag: "--ws-token-sha256", Kind: "file", Vals: ""},
		{Flag: "--ws-shared-secret-file", Kind: "file", Vals: ""},
		{Flag: "--ws-issuer", Kind: "file", Vals: ""},
		{Flag: "--ws-audience", Kind: "file", Vals: ""},
		{Flag: "--ws-max-clock-skew-seconds", Kind: "file", Vals: ""},
		{Flag: "--config", Kind: "file", Vals: ""},
		{Flag: "-c", Kind: "file", Vals: ""},
		{Flag: "--enable", Kind: "file", Vals: ""},
		{Flag: "--disable", Kind: "file", Vals: ""},
	}},
	{Fn: "codex__app__server__daemon", Opts: "-c -h --config --enable --disable --help bootstrap start restart enable-remote-control disable-remote-control stop version pid-update-loop help", Level: 3, Flags: []bashFlagDetail{
		{Flag: "--config", Kind: "file", Vals: ""},
		{Flag: "-c", Kind: "file", Vals: ""},
		{Flag: "--enable", Kind: "file", Vals: ""},
		{Flag: "--disable", Kind: "file", Vals: ""},
	}},
	{Fn: "codex__app__server__daemon__bootstrap", Opts: "-c -h --remote-control --config --enable --disable --help", Level: 4, Flags: []bashFlagDetail{
		{Flag: "--config", Kind: "file", Vals: ""},
		{Flag: "-c", Kind: "file", Vals: ""},
		{Flag: "--enable", Kind: "file", Vals: ""},
		{Flag: "--disable", Kind: "file", Vals: ""},
	}},
	{Fn: "codex__app__server__daemon__disable__remote__control", Opts: "-c -h --config --enable --disable --help", Level: 4, Flags: []bashFlagDetail{
		{Flag: "--config", Kind: "file", Vals: ""},
		{Flag: "-c", Kind: "file", Vals: ""},
		{Flag: "--enable", Kind: "file", Vals: ""},
		{Flag: "--disable", Kind: "file", Vals: ""},
	}},
	{Fn: "codex__app__server__daemon__enable__remote__control", Opts: "-c -h --config --enable --disable --help", Level: 4, Flags: []bashFlagDetail{
		{Flag: "--config", Kind: "file", Vals: ""},
		{Flag: "-c", Kind: "file", Vals: ""},
		{Flag: "--enable", Kind: "file", Vals: ""},
		{Flag: "--disable", Kind: "file", Vals: ""},
	}},
	{Fn: "codex__app__server__daemon__help", Opts: "bootstrap start restart enable-remote-control disable-remote-control stop version pid-update-loop help", Level: 4},
	{Fn: "codex__app__server__daemon__help__bootstrap", Opts: "", Level: 5},
	{Fn: "codex__app__server__daemon__help__disable__remote__control", Opts: "", Level: 5},
	{Fn: "codex__app__server__daemon__help__enable__remote__control", Opts: "", Level: 5},
	{Fn: "codex__app__server__daemon__help__help", Opts: "", Level: 5},
	{Fn: "codex__app__server__daemon__help__pid__update__loop", Opts: "", Level: 5},
	{Fn: "codex__app__server__daemon__help__restart", Opts: "", Level: 5},
	{Fn: "codex__app__server__daemon__help__start", Opts: "", Level: 5},
	{Fn: "codex__app__server__daemon__help__stop", Opts: "", Level: 5},
	{Fn: "codex__app__server__daemon__help__version", Opts: "", Level: 5},
	{Fn: "codex__app__server__daemon__pid__update__loop", Opts: "-c -h --config --enable --disable --help", Level: 4, Flags: []bashFlagDetail{
		{Flag: "--config", Kind: "file", Vals: ""},
		{Flag: "-c", Kind: "file", Vals: ""},
		{Flag: "--enable", Kind: "file", Vals: ""},
		{Flag: "--disable", Kind: "file", Vals: ""},
	}},
	{Fn: "codex__app__server__daemon__restart", Opts: "-c -h --config --enable --disable --help", Level: 4, Flags: []bashFlagDetail{
		{Flag: "--config", Kind: "file", Vals: ""},
		{Flag: "-c", Kind: "file", Vals: ""},
		{Flag: "--enable", Kind: "file", Vals: ""},
		{Flag: "--disable", Kind: "file", Vals: ""},
	}},
	{Fn: "codex__app__server__daemon__start", Opts: "-c -h --config --enable --disable --help", Level: 4, Flags: []bashFlagDetail{
		{Flag: "--config", Kind: "file", Vals: ""},
		{Flag: "-c", Kind: "file", Vals: ""},
		{Flag: "--enable", Kind: "file", Vals: ""},
		{Flag: "--disable", Kind: "file", Vals: ""},
	}},
	{Fn: "codex__app__server__daemon__stop", Opts: "-c -h --config --enable --disable --help", Level: 4, Flags: []bashFlagDetail{
		{Flag: "--config", Kind: "file", Vals: ""},
		{Flag: "-c", Kind: "file", Vals: ""},
		{Flag: "--enable", Kind: "file", Vals: ""},
		{Flag: "--disable", Kind: "file", Vals: ""},
	}},
	{Fn: "codex__app__server__daemon__version", Opts: "-c -h --config --enable --disable --help", Level: 4, Flags: []bashFlagDetail{
		{Flag: "--config", Kind: "file", Vals: ""},
		{Flag: "-c", Kind: "file", Vals: ""},
		{Flag: "--enable", Kind: "file", Vals: ""},
		{Flag: "--disable", Kind: "file", Vals: ""},
	}},
	{Fn: "codex__app__server__generate__internal__json__schema", Opts: "-o -c -h --out --config --enable --disable --help", Level: 3, Flags: []bashFlagDetail{
		{Flag: "--out", Kind: "file", Vals: ""},
		{Flag: "-o", Kind: "file", Vals: ""},
		{Flag: "--config", Kind: "file", Vals: ""},
		{Flag: "-c", Kind: "file", Vals: ""},
		{Flag: "--enable", Kind: "file", Vals: ""},
		{Flag: "--disable", Kind: "file", Vals: ""},
	}},
	{Fn: "codex__app__server__generate__json__schema", Opts: "-o -c -h --out --experimental --config --enable --disable --help", Level: 3, Flags: []bashFlagDetail{
		{Flag: "--out", Kind: "file", Vals: ""},
		{Flag: "-o", Kind: "file", Vals: ""},
		{Flag: "--config", Kind: "file", Vals: ""},
		{Flag: "-c", Kind: "file", Vals: ""},
		{Flag: "--enable", Kind: "file", Vals: ""},
		{Flag: "--disable", Kind: "file", Vals: ""},
	}},
	{Fn: "codex__app__server__generate__ts", Opts: "-o -p -c -h --out --prettier --experimental --config --enable --disable --help", Level: 3, Flags: []bashFlagDetail{
		{Flag: "--out", Kind: "file", Vals: ""},
		{Flag: "-o", Kind: "file", Vals: ""},
		{Flag: "--prettier", Kind: "file", Vals: ""},
		{Flag: "-p", Kind: "file", Vals: ""},
		{Flag: "--config", Kind: "file", Vals: ""},
		{Flag: "-c", Kind: "file", Vals: ""},
		{Flag: "--enable", Kind: "file", Vals: ""},
		{Flag: "--disable", Kind: "file", Vals: ""},
	}},
	{Fn: "codex__app__server__help", Opts: "daemon proxy generate-ts generate-json-schema generate-internal-json-schema help", Level: 3},
	{Fn: "codex__app__server__help__daemon", Opts: "bootstrap start restart enable-remote-control disable-remote-control stop version pid-update-loop", Level: 4},
	{Fn: "codex__app__server__help__daemon__bootstrap", Opts: "", Level: 5},
	{Fn: "codex__app__server__help__daemon__disable__remote__control", Opts: "", Level: 5},
	{Fn: "codex__app__server__help__daemon__enable__remote__control", Opts: "", Level: 5},
	{Fn: "codex__app__server__help__daemon__pid__update__loop", Opts: "", Level: 5},
	{Fn: "codex__app__server__help__daemon__restart", Opts: "", Level: 5},
	{Fn: "codex__app__server__help__daemon__start", Opts: "", Level: 5},
	{Fn: "codex__app__server__help__daemon__stop", Opts: "", Level: 5},
	{Fn: "codex__app__server__help__daemon__version", Opts: "", Level: 5},
	{Fn: "codex__app__server__help__generate__internal__json__schema", Opts: "", Level: 4},
	{Fn: "codex__app__server__help__generate__json__schema", Opts: "", Level: 4},
	{Fn: "codex__app__server__help__generate__ts", Opts: "", Level: 4},
	{Fn: "codex__app__server__help__help", Opts: "", Level: 4},
	{Fn: "codex__app__server__help__proxy", Opts: "", Level: 4},
	{Fn: "codex__app__server__proxy", Opts: "-c -h --sock --config --enable --disable --help", Level: 3, Flags: []bashFlagDetail{
		{Flag: "--sock", Kind: "file", Vals: ""},
		{Flag: "--config", Kind: "file", Vals: ""},
		{Flag: "-c", Kind: "file", Vals: ""},
		{Flag: "--enable", Kind: "file", Vals: ""},
		{Flag: "--disable", Kind: "file", Vals: ""},
	}},
	{Fn: "codex__apply", Opts: "-c -h --config --enable --disable --help <TASK_ID>", Level: 2, Flags: []bashFlagDetail{
		{Flag: "--config", Kind: "file", Vals: ""},
		{Flag: "-c", Kind: "file", Vals: ""},
		{Flag: "--enable", Kind: "file", Vals: ""},
		{Flag: "--disable", Kind: "file", Vals: ""},
	}},
	{Fn: "codex__archive", Opts: "-i -m -p -s -C -c -h --remote --remote-auth-token-env --image --model --oss --local-provider --profile --sandbox --dangerously-bypass-approvals-and-sandbox --dangerously-bypass-hook-trust --cd --add-dir --strict-config --config --enable --disable --help <SESSION>", Level: 2, Flags: []bashFlagDetail{
		{Flag: "--remote", Kind: "file", Vals: ""},
		{Flag: "--remote-auth-token-env", Kind: "file", Vals: ""},
		{Flag: "--image", Kind: "file", Vals: ""},
		{Flag: "-i", Kind: "file", Vals: ""},
		{Flag: "--model", Kind: "file", Vals: ""},
		{Flag: "-m", Kind: "file", Vals: ""},
		{Flag: "--local-provider", Kind: "file", Vals: ""},
		{Flag: "--profile", Kind: "file", Vals: ""},
		{Flag: "-p", Kind: "file", Vals: ""},
		{Flag: "--sandbox", Kind: "vals", Vals: "read-only workspace-write danger-full-access"},
		{Flag: "-s", Kind: "vals", Vals: "read-only workspace-write danger-full-access"},
		{Flag: "--cd", Kind: "file", Vals: ""},
		{Flag: "-C", Kind: "file", Vals: ""},
		{Flag: "--add-dir", Kind: "dir", Vals: ""},
		{Flag: "--config", Kind: "file", Vals: ""},
		{Flag: "-c", Kind: "file", Vals: ""},
		{Flag: "--enable", Kind: "file", Vals: ""},
		{Flag: "--disable", Kind: "file", Vals: ""},
	}},
	{Fn: "codex__cloud", Opts: "-c -h -V --config --enable --disable --help --version exec status list apply diff help", Level: 2, Flags: []bashFlagDetail{
		{Flag: "--config", Kind: "file", Vals: ""},
		{Flag: "-c", Kind: "file", Vals: ""},
		{Flag: "--enable", Kind: "file", Vals: ""},
		{Flag: "--disable", Kind: "file", Vals: ""},
	}},
	{Fn: "codex__cloud__apply", Opts: "-c -h --attempt --config --enable --disable --help <TASK_ID>", Level: 3, Flags: []bashFlagDetail{
		{Flag: "--attempt", Kind: "file", Vals: ""},
		{Flag: "--config", Kind: "file", Vals: ""},
		{Flag: "-c", Kind: "file", Vals: ""},
		{Flag: "--enable", Kind: "file", Vals: ""},
		{Flag: "--disable", Kind: "file", Vals: ""},
	}},
	{Fn: "codex__cloud__diff", Opts: "-c -h --attempt --config --enable --disable --help <TASK_ID>", Level: 3, Flags: []bashFlagDetail{
		{Flag: "--attempt", Kind: "file", Vals: ""},
		{Flag: "--config", Kind: "file", Vals: ""},
		{Flag: "-c", Kind: "file", Vals: ""},
		{Flag: "--enable", Kind: "file", Vals: ""},
		{Flag: "--disable", Kind: "file", Vals: ""},
	}},
	{Fn: "codex__cloud__exec", Opts: "-c -h --env --attempts --branch --config --enable --disable --help [QUERY]", Level: 3, Flags: []bashFlagDetail{
		{Flag: "--env", Kind: "file", Vals: ""},
		{Flag: "--attempts", Kind: "file", Vals: ""},
		{Flag: "--branch", Kind: "file", Vals: ""},
		{Flag: "--config", Kind: "file", Vals: ""},
		{Flag: "-c", Kind: "file", Vals: ""},
		{Flag: "--enable", Kind: "file", Vals: ""},
		{Flag: "--disable", Kind: "file", Vals: ""},
	}},
	{Fn: "codex__cloud__help", Opts: "exec status list apply diff help", Level: 3},
	{Fn: "codex__cloud__help__apply", Opts: "", Level: 4},
	{Fn: "codex__cloud__help__diff", Opts: "", Level: 4},
	{Fn: "codex__cloud__help__exec", Opts: "", Level: 4},
	{Fn: "codex__cloud__help__help", Opts: "", Level: 4},
	{Fn: "codex__cloud__help__list", Opts: "", Level: 4},
	{Fn: "codex__cloud__help__status", Opts: "", Level: 4},
	{Fn: "codex__cloud__list", Opts: "-c -h --env --limit --cursor --json --config --enable --disable --help", Level: 3, Flags: []bashFlagDetail{
		{Flag: "--env", Kind: "file", Vals: ""},
		{Flag: "--limit", Kind: "file", Vals: ""},
		{Flag: "--cursor", Kind: "file", Vals: ""},
		{Flag: "--config", Kind: "file", Vals: ""},
		{Flag: "-c", Kind: "file", Vals: ""},
		{Flag: "--enable", Kind: "file", Vals: ""},
		{Flag: "--disable", Kind: "file", Vals: ""},
	}},
	{Fn: "codex__cloud__status", Opts: "-c -h --config --enable --disable --help <TASK_ID>", Level: 3, Flags: []bashFlagDetail{
		{Flag: "--config", Kind: "file", Vals: ""},
		{Flag: "-c", Kind: "file", Vals: ""},
		{Flag: "--enable", Kind: "file", Vals: ""},
		{Flag: "--disable", Kind: "file", Vals: ""},
	}},
	{Fn: "codex__completion", Opts: "-c -h --config --enable --disable --help bash elvish fish powershell zsh", Level: 2, Flags: []bashFlagDetail{
		{Flag: "--config", Kind: "file", Vals: ""},
		{Flag: "-c", Kind: "file", Vals: ""},
		{Flag: "--enable", Kind: "file", Vals: ""},
		{Flag: "--disable", Kind: "file", Vals: ""},
	}},
	{Fn: "codex__debug", Opts: "-c -h --config --enable --disable --help models app-server prompt-input trace-reduce clear-memories help", Level: 2, Flags: []bashFlagDetail{
		{Flag: "--config", Kind: "file", Vals: ""},
		{Flag: "-c", Kind: "file", Vals: ""},
		{Flag: "--enable", Kind: "file", Vals: ""},
		{Flag: "--disable", Kind: "file", Vals: ""},
	}},
	{Fn: "codex__debug__app__server", Opts: "-c -h --config --enable --disable --help send-message-v2 help", Level: 3, Flags: []bashFlagDetail{
		{Flag: "--config", Kind: "file", Vals: ""},
		{Flag: "-c", Kind: "file", Vals: ""},
		{Flag: "--enable", Kind: "file", Vals: ""},
		{Flag: "--disable", Kind: "file", Vals: ""},
	}},
	{Fn: "codex__debug__app__server__help", Opts: "send-message-v2 help", Level: 4},
	{Fn: "codex__debug__app__server__help__help", Opts: "", Level: 5},
	{Fn: "codex__debug__app__server__help__send__message__v2", Opts: "", Level: 5},
	{Fn: "codex__debug__app__server__send__message__v2", Opts: "-c -h --config --enable --disable --help <USER_MESSAGE>", Level: 4, Flags: []bashFlagDetail{
		{Flag: "--config", Kind: "file", Vals: ""},
		{Flag: "-c", Kind: "file", Vals: ""},
		{Flag: "--enable", Kind: "file", Vals: ""},
		{Flag: "--disable", Kind: "file", Vals: ""},
	}},
	{Fn: "codex__debug__clear__memories", Opts: "-c -h --config --enable --disable --help", Level: 3, Flags: []bashFlagDetail{
		{Flag: "--config", Kind: "file", Vals: ""},
		{Flag: "-c", Kind: "file", Vals: ""},
		{Flag: "--enable", Kind: "file", Vals: ""},
		{Flag: "--disable", Kind: "file", Vals: ""},
	}},
	{Fn: "codex__debug__help", Opts: "models app-server prompt-input trace-reduce clear-memories help", Level: 3},
	{Fn: "codex__debug__help__app__server", Opts: "send-message-v2", Level: 4},
	{Fn: "codex__debug__help__app__server__send__message__v2", Opts: "", Level: 5},
	{Fn: "codex__debug__help__clear__memories", Opts: "", Level: 4},
	{Fn: "codex__debug__help__help", Opts: "", Level: 4},
	{Fn: "codex__debug__help__models", Opts: "", Level: 4},
	{Fn: "codex__debug__help__prompt__input", Opts: "", Level: 4},
	{Fn: "codex__debug__help__trace__reduce", Opts: "", Level: 4},
	{Fn: "codex__debug__models", Opts: "-c -h --bundled --config --enable --disable --help", Level: 3, Flags: []bashFlagDetail{
		{Flag: "--config", Kind: "file", Vals: ""},
		{Flag: "-c", Kind: "file", Vals: ""},
		{Flag: "--enable", Kind: "file", Vals: ""},
		{Flag: "--disable", Kind: "file", Vals: ""},
	}},
	{Fn: "codex__debug__prompt__input", Opts: "-i -c -h --image --config --enable --disable --help [PROMPT]", Level: 3, Flags: []bashFlagDetail{
		{Flag: "--image", Kind: "file", Vals: ""},
		{Flag: "-i", Kind: "file", Vals: ""},
		{Flag: "--config", Kind: "file", Vals: ""},
		{Flag: "-c", Kind: "file", Vals: ""},
		{Flag: "--enable", Kind: "file", Vals: ""},
		{Flag: "--disable", Kind: "file", Vals: ""},
	}},
	{Fn: "codex__debug__trace__reduce", Opts: "-o -c -h --output --config --enable --disable --help <TRACE_BUNDLE>", Level: 3, Flags: []bashFlagDetail{
		{Flag: "--output", Kind: "file", Vals: ""},
		{Flag: "-o", Kind: "file", Vals: ""},
		{Flag: "--config", Kind: "file", Vals: ""},
		{Flag: "-c", Kind: "file", Vals: ""},
		{Flag: "--enable", Kind: "file", Vals: ""},
		{Flag: "--disable", Kind: "file", Vals: ""},
	}},
	{Fn: "codex__doctor", Opts: "-c -h --json --summary --all --no-color --ascii --config --enable --disable --help", Level: 2, Flags: []bashFlagDetail{
		{Flag: "--config", Kind: "file", Vals: ""},
		{Flag: "-c", Kind: "file", Vals: ""},
		{Flag: "--enable", Kind: "file", Vals: ""},
		{Flag: "--disable", Kind: "file", Vals: ""},
	}},
	{Fn: "codex__exec", Opts: "-i -p -s -C -m -o -c -h -V --strict-config --image --oss --local-provider --profile --sandbox --cd --add-dir --model --dangerously-bypass-approvals-and-sandbox --dangerously-bypass-hook-trust --skip-git-repo-check --ephemeral --ignore-user-config --ignore-rules --full-auto --output-schema --color --json --output-last-message --config --enable --disable --help --version [PROMPT] resume review help", Level: 2, Flags: []bashFlagDetail{
		{Flag: "--image", Kind: "file", Vals: ""},
		{Flag: "-i", Kind: "file", Vals: ""},
		{Flag: "--local-provider", Kind: "file", Vals: ""},
		{Flag: "--profile", Kind: "file", Vals: ""},
		{Flag: "-p", Kind: "file", Vals: ""},
		{Flag: "--sandbox", Kind: "vals", Vals: "read-only workspace-write danger-full-access"},
		{Flag: "-s", Kind: "vals", Vals: "read-only workspace-write danger-full-access"},
		{Flag: "--cd", Kind: "file", Vals: ""},
		{Flag: "-C", Kind: "file", Vals: ""},
		{Flag: "--add-dir", Kind: "dir", Vals: ""},
		{Flag: "--model", Kind: "file", Vals: ""},
		{Flag: "-m", Kind: "file", Vals: ""},
		{Flag: "--output-schema", Kind: "file", Vals: ""},
		{Flag: "--color", Kind: "vals", Vals: "always never auto"},
		{Flag: "--output-last-message", Kind: "file", Vals: ""},
		{Flag: "-o", Kind: "file", Vals: ""},
		{Flag: "--config", Kind: "file", Vals: ""},
		{Flag: "-c", Kind: "file", Vals: ""},
		{Flag: "--enable", Kind: "file", Vals: ""},
		{Flag: "--disable", Kind: "file", Vals: ""},
	}},
	{Fn: "codex__exec__server", Opts: "-c -h --strict-config --listen --remote --environment-id --name --use-agent-identity-auth --config --enable --disable --help", Level: 2, Flags: []bashFlagDetail{
		{Flag: "--listen", Kind: "file", Vals: ""},
		{Flag: "--remote", Kind: "file", Vals: ""},
		{Flag: "--environment-id", Kind: "file", Vals: ""},
		{Flag: "--name", Kind: "file", Vals: ""},
		{Flag: "--config", Kind: "file", Vals: ""},
		{Flag: "-c", Kind: "file", Vals: ""},
		{Flag: "--enable", Kind: "file", Vals: ""},
		{Flag: "--disable", Kind: "file", Vals: ""},
	}},
	{Fn: "codex__exec__help", Opts: "resume review help", Level: 3},
	{Fn: "codex__exec__help__help", Opts: "", Level: 4},
	{Fn: "codex__exec__help__resume", Opts: "", Level: 4},
	{Fn: "codex__exec__help__review", Opts: "", Level: 4},
	{Fn: "codex__exec__resume", Opts: "-i -m -o -c -h --last --all --image --strict-config --model --dangerously-bypass-approvals-and-sandbox --dangerously-bypass-hook-trust --skip-git-repo-check --ephemeral --ignore-user-config --ignore-rules --full-auto --output-schema --json --output-last-message --config --enable --disable --help [SESSION_ID] [PROMPT]", Level: 3, Flags: []bashFlagDetail{
		{Flag: "--image", Kind: "file", Vals: ""},
		{Flag: "-i", Kind: "file", Vals: ""},
		{Flag: "--model", Kind: "file", Vals: ""},
		{Flag: "-m", Kind: "file", Vals: ""},
		{Flag: "--output-schema", Kind: "file", Vals: ""},
		{Flag: "--output-last-message", Kind: "file", Vals: ""},
		{Flag: "-o", Kind: "file", Vals: ""},
		{Flag: "--config", Kind: "file", Vals: ""},
		{Flag: "-c", Kind: "file", Vals: ""},
		{Flag: "--enable", Kind: "file", Vals: ""},
		{Flag: "--disable", Kind: "file", Vals: ""},
	}},
	{Fn: "codex__exec__review", Opts: "-m -o -c -h --uncommitted --base --commit --title --strict-config --model --dangerously-bypass-approvals-and-sandbox --dangerously-bypass-hook-trust --skip-git-repo-check --ephemeral --ignore-user-config --ignore-rules --full-auto --output-schema --json --output-last-message --config --enable --disable --help [PROMPT]", Level: 3, Flags: []bashFlagDetail{
		{Flag: "--base", Kind: "file", Vals: ""},
		{Flag: "--commit", Kind: "file", Vals: ""},
		{Flag: "--title", Kind: "file", Vals: ""},
		{Flag: "--model", Kind: "file", Vals: ""},
		{Flag: "-m", Kind: "file", Vals: ""},
		{Flag: "--output-schema", Kind: "file", Vals: ""},
		{Flag: "--output-last-message", Kind: "file", Vals: ""},
		{Flag: "-o", Kind: "file", Vals: ""},
		{Flag: "--config", Kind: "file", Vals: ""},
		{Flag: "-c", Kind: "file", Vals: ""},
		{Flag: "--enable", Kind: "file", Vals: ""},
		{Flag: "--disable", Kind: "file", Vals: ""},
	}},
	{Fn: "codex__execpolicy", Opts: "-c -h --config --enable --disable --help check help", Level: 2, Flags: []bashFlagDetail{
		{Flag: "--config", Kind: "file", Vals: ""},
		{Flag: "-c", Kind: "file", Vals: ""},
		{Flag: "--enable", Kind: "file", Vals: ""},
		{Flag: "--disable", Kind: "file", Vals: ""},
	}},
	{Fn: "codex__execpolicy__check", Opts: "-r -c -h --rules --pretty --resolve-host-executables --config --enable --disable --help <COMMAND>...", Level: 3, Flags: []bashFlagDetail{
		{Flag: "--rules", Kind: "file", Vals: ""},
		{Flag: "-r", Kind: "file", Vals: ""},
		{Flag: "--config", Kind: "file", Vals: ""},
		{Flag: "-c", Kind: "file", Vals: ""},
		{Flag: "--enable", Kind: "file", Vals: ""},
		{Flag: "--disable", Kind: "file", Vals: ""},
	}},
	{Fn: "codex__execpolicy__help", Opts: "check help", Level: 3},
	{Fn: "codex__execpolicy__help__check", Opts: "", Level: 4},
	{Fn: "codex__execpolicy__help__help", Opts: "", Level: 4},
	{Fn: "codex__features", Opts: "-c -h --config --enable --disable --help list enable disable help", Level: 2, Flags: []bashFlagDetail{
		{Flag: "--config", Kind: "file", Vals: ""},
		{Flag: "-c", Kind: "file", Vals: ""},
		{Flag: "--enable", Kind: "file", Vals: ""},
		{Flag: "--disable", Kind: "file", Vals: ""},
	}},
	{Fn: "codex__features__disable", Opts: "-c -h --config --enable --disable --help <FEATURE>", Level: 3, Flags: []bashFlagDetail{
		{Flag: "--config", Kind: "file", Vals: ""},
		{Flag: "-c", Kind: "file", Vals: ""},
		{Flag: "--enable", Kind: "file", Vals: ""},
		{Flag: "--disable", Kind: "file", Vals: ""},
	}},
	{Fn: "codex__features__enable", Opts: "-c -h --config --enable --disable --help <FEATURE>", Level: 3, Flags: []bashFlagDetail{
		{Flag: "--config", Kind: "file", Vals: ""},
		{Flag: "-c", Kind: "file", Vals: ""},
		{Flag: "--enable", Kind: "file", Vals: ""},
		{Flag: "--disable", Kind: "file", Vals: ""},
	}},
	{Fn: "codex__features__help", Opts: "list enable disable help", Level: 3},
	{Fn: "codex__features__help__disable", Opts: "", Level: 4},
	{Fn: "codex__features__help__enable", Opts: "", Level: 4},
	{Fn: "codex__features__help__help", Opts: "", Level: 4},
	{Fn: "codex__features__help__list", Opts: "", Level: 4},
	{Fn: "codex__features__list", Opts: "-c -h --config --enable --disable --help", Level: 3, Flags: []bashFlagDetail{
		{Flag: "--config", Kind: "file", Vals: ""},
		{Flag: "-c", Kind: "file", Vals: ""},
		{Flag: "--enable", Kind: "file", Vals: ""},
		{Flag: "--disable", Kind: "file", Vals: ""},
	}},
	{Fn: "codex__fork", Opts: "-i -m -p -s -C -a -c -h -V --last --all --remote --remote-auth-token-env --strict-config --image --model --oss --local-provider --profile --sandbox --dangerously-bypass-hook-trust --cd --add-dir --dangerously-bypass-approvals-and-sandbox --ask-for-approval --search --no-alt-screen --config --enable --disable --help --version [SESSION_ID] [PROMPT]", Level: 2, Flags: []bashFlagDetail{
		{Flag: "--remote", Kind: "file", Vals: ""},
		{Flag: "--remote-auth-token-env", Kind: "file", Vals: ""},
		{Flag: "--image", Kind: "file", Vals: ""},
		{Flag: "-i", Kind: "file", Vals: ""},
		{Flag: "--model", Kind: "file", Vals: ""},
		{Flag: "-m", Kind: "file", Vals: ""},
		{Flag: "--local-provider", Kind: "file", Vals: ""},
		{Flag: "--profile", Kind: "file", Vals: ""},
		{Flag: "-p", Kind: "file", Vals: ""},
		{Flag: "--sandbox", Kind: "vals", Vals: "read-only workspace-write danger-full-access"},
		{Flag: "-s", Kind: "vals", Vals: "read-only workspace-write danger-full-access"},
		{Flag: "--cd", Kind: "file", Vals: ""},
		{Flag: "-C", Kind: "file", Vals: ""},
		{Flag: "--add-dir", Kind: "dir", Vals: ""},
		{Flag: "--ask-for-approval", Kind: "vals", Vals: "untrusted on-failure on-request never"},
		{Flag: "-a", Kind: "vals", Vals: "untrusted on-failure on-request never"},
		{Flag: "--config", Kind: "file", Vals: ""},
		{Flag: "-c", Kind: "file", Vals: ""},
		{Flag: "--enable", Kind: "file", Vals: ""},
		{Flag: "--disable", Kind: "file", Vals: ""},
	}},
	{Fn: "codex__help", Opts: "exec review login logout mcp plugin mcp-server app-server remote-control app completion update doctor sandbox debug execpolicy apply resume archive unarchive fork cloud responses-api-proxy stdio-to-uds exec-server features help", Level: 2},
	{Fn: "codex__help__app", Opts: "", Level: 3},
	{Fn: "codex__help__app__server", Opts: "daemon proxy generate-ts generate-json-schema generate-internal-json-schema", Level: 3},
	{Fn: "codex__help__app__server__daemon", Opts: "bootstrap start restart enable-remote-control disable-remote-control stop version pid-update-loop", Level: 4},
	{Fn: "codex__help__app__server__daemon__bootstrap", Opts: "", Level: 5},
	{Fn: "codex__help__app__server__daemon__disable__remote__control", Opts: "", Level: 5},
	{Fn: "codex__help__app__server__daemon__enable__remote__control", Opts: "", Level: 5},
	{Fn: "codex__help__app__server__daemon__pid__update__loop", Opts: "", Level: 5},
	{Fn: "codex__help__app__server__daemon__restart", Opts: "", Level: 5},
	{Fn: "codex__help__app__server__daemon__start", Opts: "", Level: 5},
	{Fn: "codex__help__app__server__daemon__stop", Opts: "", Level: 5},
	{Fn: "codex__help__app__server__daemon__version", Opts: "", Level: 5},
	{Fn: "codex__help__app__server__generate__internal__json__schema", Opts: "", Level: 4},
	{Fn: "codex__help__app__server__generate__json__schema", Opts: "", Level: 4},
	{Fn: "codex__help__app__server__generate__ts", Opts: "", Level: 4},
	{Fn: "codex__help__app__server__proxy", Opts: "", Level: 4},
	{Fn: "codex__help__apply", Opts: "", Level: 3},
	{Fn: "codex__help__archive", Opts: "", Level: 3},
	{Fn: "codex__help__cloud", Opts: "exec status list apply diff", Level: 3},
	{Fn: "codex__help__cloud__apply", Opts: "", Level: 4},
	{Fn: "codex__help__cloud__diff", Opts: "", Level: 4},
	{Fn: "codex__help__cloud__exec", Opts: "", Level: 4},
	{Fn: "codex__help__cloud__list", Opts: "", Level: 4},
	{Fn: "codex__help__cloud__status", Opts: "", Level: 4},
	{Fn: "codex__help__completion", Opts: "", Level: 3},
	{Fn: "codex__help__debug", Opts: "models app-server prompt-input trace-reduce clear-memories", Level: 3},
	{Fn: "codex__help__debug__app__server", Opts: "send-message-v2", Level: 4},
	{Fn: "codex__help__debug__app__server__send__message__v2", Opts: "", Level: 5},
	{Fn: "codex__help__debug__clear__memories", Opts: "", Level: 4},
	{Fn: "codex__help__debug__models", Opts: "", Level: 4},
	{Fn: "codex__help__debug__prompt__input", Opts: "", Level: 4},
	{Fn: "codex__help__debug__trace__reduce", Opts: "", Level: 4},
	{Fn: "codex__help__doctor", Opts: "", Level: 3},
	{Fn: "codex__help__exec", Opts: "resume review", Level: 3},
	{Fn: "codex__help__exec__server", Opts: "", Level: 3},
	{Fn: "codex__help__exec__resume", Opts: "", Level: 4},
	{Fn: "codex__help__exec__review", Opts: "", Level: 4},
	{Fn: "codex__help__execpolicy", Opts: "check", Level: 3},
	{Fn: "codex__help__execpolicy__check", Opts: "", Level: 4},
	{Fn: "codex__help__features", Opts: "list enable disable", Level: 3},
	{Fn: "codex__help__features__disable", Opts: "", Level: 4},
	{Fn: "codex__help__features__enable", Opts: "", Level: 4},
	{Fn: "codex__help__features__list", Opts: "", Level: 4},
	{Fn: "codex__help__fork", Opts: "", Level: 3},
	{Fn: "codex__help__help", Opts: "", Level: 3},
	{Fn: "codex__help__login", Opts: "status", Level: 3},
	{Fn: "codex__help__login__status", Opts: "", Level: 4},
	{Fn: "codex__help__logout", Opts: "", Level: 3},
	{Fn: "codex__help__mcp", Opts: "list get add remove login logout", Level: 3},
	{Fn: "codex__help__mcp__server", Opts: "", Level: 3},
	{Fn: "codex__help__mcp__add", Opts: "", Level: 4},
	{Fn: "codex__help__mcp__get", Opts: "", Level: 4},
	{Fn: "codex__help__mcp__list", Opts: "", Level: 4},
	{Fn: "codex__help__mcp__login", Opts: "", Level: 4},
	{Fn: "codex__help__mcp__logout", Opts: "", Level: 4},
	{Fn: "codex__help__mcp__remove", Opts: "", Level: 4},
	{Fn: "codex__help__plugin", Opts: "add list marketplace remove", Level: 3},
	{Fn: "codex__help__plugin__add", Opts: "", Level: 4},
	{Fn: "codex__help__plugin__list", Opts: "", Level: 4},
	{Fn: "codex__help__plugin__marketplace", Opts: "add list upgrade remove", Level: 4},
	{Fn: "codex__help__plugin__marketplace__add", Opts: "", Level: 5},
	{Fn: "codex__help__plugin__marketplace__list", Opts: "", Level: 5},
	{Fn: "codex__help__plugin__marketplace__remove", Opts: "", Level: 5},
	{Fn: "codex__help__plugin__marketplace__upgrade", Opts: "", Level: 5},
	{Fn: "codex__help__plugin__remove", Opts: "", Level: 4},
	{Fn: "codex__help__remote__control", Opts: "start stop", Level: 3},
	{Fn: "codex__help__remote__control__start", Opts: "", Level: 4},
	{Fn: "codex__help__remote__control__stop", Opts: "", Level: 4},
	{Fn: "codex__help__responses__api__proxy", Opts: "", Level: 3},
	{Fn: "codex__help__resume", Opts: "", Level: 3},
	{Fn: "codex__help__review", Opts: "", Level: 3},
	{Fn: "codex__help__sandbox", Opts: "", Level: 3},
	{Fn: "codex__help__stdio__to__uds", Opts: "", Level: 3},
	{Fn: "codex__help__unarchive", Opts: "", Level: 3},
	{Fn: "codex__help__update", Opts: "", Level: 3},
	{Fn: "codex__login", Opts: "-c -h --with-api-key --with-access-token --api-key --device-auth --experimental_issuer --experimental_client-id --config --enable --disable --help status help", Level: 2, Flags: []bashFlagDetail{
		{Flag: "--api-key", Kind: "file", Vals: ""},
		{Flag: "--experimental_issuer", Kind: "file", Vals: ""},
		{Flag: "--experimental_client-id", Kind: "file", Vals: ""},
		{Flag: "--config", Kind: "file", Vals: ""},
		{Flag: "-c", Kind: "file", Vals: ""},
		{Flag: "--enable", Kind: "file", Vals: ""},
		{Flag: "--disable", Kind: "file", Vals: ""},
	}},
	{Fn: "codex__login__help", Opts: "status help", Level: 3},
	{Fn: "codex__login__help__help", Opts: "", Level: 4},
	{Fn: "codex__login__help__status", Opts: "", Level: 4},
	{Fn: "codex__login__status", Opts: "-c -h --config --enable --disable --help", Level: 3, Flags: []bashFlagDetail{
		{Flag: "--config", Kind: "file", Vals: ""},
		{Flag: "-c", Kind: "file", Vals: ""},
		{Flag: "--enable", Kind: "file", Vals: ""},
		{Flag: "--disable", Kind: "file", Vals: ""},
	}},
	{Fn: "codex__logout", Opts: "-c -h --config --enable --disable --help", Level: 2, Flags: []bashFlagDetail{
		{Flag: "--config", Kind: "file", Vals: ""},
		{Flag: "-c", Kind: "file", Vals: ""},
		{Flag: "--enable", Kind: "file", Vals: ""},
		{Flag: "--disable", Kind: "file", Vals: ""},
	}},
	{Fn: "codex__mcp", Opts: "-c -h --config --enable --disable --help list get add remove login logout help", Level: 2, Flags: []bashFlagDetail{
		{Flag: "--config", Kind: "file", Vals: ""},
		{Flag: "-c", Kind: "file", Vals: ""},
		{Flag: "--enable", Kind: "file", Vals: ""},
		{Flag: "--disable", Kind: "file", Vals: ""},
	}},
	{Fn: "codex__mcp__server", Opts: "-c -h --strict-config --config --enable --disable --help", Level: 2, Flags: []bashFlagDetail{
		{Flag: "--config", Kind: "file", Vals: ""},
		{Flag: "-c", Kind: "file", Vals: ""},
		{Flag: "--enable", Kind: "file", Vals: ""},
		{Flag: "--disable", Kind: "file", Vals: ""},
	}},
	{Fn: "codex__mcp__add", Opts: "-c -h --env --url --bearer-token-env-var --oauth-client-id --oauth-resource --config --enable --disable --help <NAME> [COMMAND]...", Level: 3, Flags: []bashFlagDetail{
		{Flag: "--env", Kind: "file", Vals: ""},
		{Flag: "--url", Kind: "file", Vals: ""},
		{Flag: "--bearer-token-env-var", Kind: "file", Vals: ""},
		{Flag: "--oauth-client-id", Kind: "file", Vals: ""},
		{Flag: "--oauth-resource", Kind: "file", Vals: ""},
		{Flag: "--config", Kind: "file", Vals: ""},
		{Flag: "-c", Kind: "file", Vals: ""},
		{Flag: "--enable", Kind: "file", Vals: ""},
		{Flag: "--disable", Kind: "file", Vals: ""},
	}},
	{Fn: "codex__mcp__get", Opts: "-c -h --json --config --enable --disable --help <NAME>", Level: 3, Flags: []bashFlagDetail{
		{Flag: "--config", Kind: "file", Vals: ""},
		{Flag: "-c", Kind: "file", Vals: ""},
		{Flag: "--enable", Kind: "file", Vals: ""},
		{Flag: "--disable", Kind: "file", Vals: ""},
	}},
	{Fn: "codex__mcp__help", Opts: "list get add remove login logout help", Level: 3},
	{Fn: "codex__mcp__help__add", Opts: "", Level: 4},
	{Fn: "codex__mcp__help__get", Opts: "", Level: 4},
	{Fn: "codex__mcp__help__help", Opts: "", Level: 4},
	{Fn: "codex__mcp__help__list", Opts: "", Level: 4},
	{Fn: "codex__mcp__help__login", Opts: "", Level: 4},
	{Fn: "codex__mcp__help__logout", Opts: "", Level: 4},
	{Fn: "codex__mcp__help__remove", Opts: "", Level: 4},
	{Fn: "codex__mcp__list", Opts: "-c -h --json --config --enable --disable --help", Level: 3, Flags: []bashFlagDetail{
		{Flag: "--config", Kind: "file", Vals: ""},
		{Flag: "-c", Kind: "file", Vals: ""},
		{Flag: "--enable", Kind: "file", Vals: ""},
		{Flag: "--disable", Kind: "file", Vals: ""},
	}},
	{Fn: "codex__mcp__login", Opts: "-c -h --scopes --config --enable --disable --help <NAME>", Level: 3, Flags: []bashFlagDetail{
		{Flag: "--scopes", Kind: "file", Vals: ""},
		{Flag: "--config", Kind: "file", Vals: ""},
		{Flag: "-c", Kind: "file", Vals: ""},
		{Flag: "--enable", Kind: "file", Vals: ""},
		{Flag: "--disable", Kind: "file", Vals: ""},
	}},
	{Fn: "codex__mcp__logout", Opts: "-c -h --config --enable --disable --help <NAME>", Level: 3, Flags: []bashFlagDetail{
		{Flag: "--config", Kind: "file", Vals: ""},
		{Flag: "-c", Kind: "file", Vals: ""},
		{Flag: "--enable", Kind: "file", Vals: ""},
		{Flag: "--disable", Kind: "file", Vals: ""},
	}},
	{Fn: "codex__mcp__remove", Opts: "-c -h --config --enable --disable --help <NAME>", Level: 3, Flags: []bashFlagDetail{
		{Flag: "--config", Kind: "file", Vals: ""},
		{Flag: "-c", Kind: "file", Vals: ""},
		{Flag: "--enable", Kind: "file", Vals: ""},
		{Flag: "--disable", Kind: "file", Vals: ""},
	}},
	{Fn: "codex__plugin", Opts: "-c -h --config --enable --disable --help add list marketplace remove help", Level: 2, Flags: []bashFlagDetail{
		{Flag: "--config", Kind: "file", Vals: ""},
		{Flag: "-c", Kind: "file", Vals: ""},
		{Flag: "--enable", Kind: "file", Vals: ""},
		{Flag: "--disable", Kind: "file", Vals: ""},
	}},
	{Fn: "codex__plugin__add", Opts: "-m -c -h --marketplace --config --enable --disable --help <PLUGIN[@MARKETPLACE]>", Level: 3, Flags: []bashFlagDetail{
		{Flag: "--marketplace", Kind: "file", Vals: ""},
		{Flag: "-m", Kind: "file", Vals: ""},
		{Flag: "--config", Kind: "file", Vals: ""},
		{Flag: "-c", Kind: "file", Vals: ""},
		{Flag: "--enable", Kind: "file", Vals: ""},
		{Flag: "--disable", Kind: "file", Vals: ""},
	}},
	{Fn: "codex__plugin__help", Opts: "add list marketplace remove help", Level: 3},
	{Fn: "codex__plugin__help__add", Opts: "", Level: 4},
	{Fn: "codex__plugin__help__help", Opts: "", Level: 4},
	{Fn: "codex__plugin__help__list", Opts: "", Level: 4},
	{Fn: "codex__plugin__help__marketplace", Opts: "add list upgrade remove", Level: 4},
	{Fn: "codex__plugin__help__marketplace__add", Opts: "", Level: 5},
	{Fn: "codex__plugin__help__marketplace__list", Opts: "", Level: 5},
	{Fn: "codex__plugin__help__marketplace__remove", Opts: "", Level: 5},
	{Fn: "codex__plugin__help__marketplace__upgrade", Opts: "", Level: 5},
	{Fn: "codex__plugin__help__remove", Opts: "", Level: 4},
	{Fn: "codex__plugin__list", Opts: "-m -c -h --marketplace --config --enable --disable --help", Level: 3, Flags: []bashFlagDetail{
		{Flag: "--marketplace", Kind: "file", Vals: ""},
		{Flag: "-m", Kind: "file", Vals: ""},
		{Flag: "--config", Kind: "file", Vals: ""},
		{Flag: "-c", Kind: "file", Vals: ""},
		{Flag: "--enable", Kind: "file", Vals: ""},
		{Flag: "--disable", Kind: "file", Vals: ""},
	}},
	{Fn: "codex__plugin__marketplace", Opts: "-c -h --config --enable --disable --help add list upgrade remove help", Level: 3, Flags: []bashFlagDetail{
		{Flag: "--config", Kind: "file", Vals: ""},
		{Flag: "-c", Kind: "file", Vals: ""},
		{Flag: "--enable", Kind: "file", Vals: ""},
		{Flag: "--disable", Kind: "file", Vals: ""},
	}},
	{Fn: "codex__plugin__marketplace__add", Opts: "-c -h --ref --sparse --config --enable --disable --help <SOURCE>", Level: 4, Flags: []bashFlagDetail{
		{Flag: "--ref", Kind: "file", Vals: ""},
		{Flag: "--sparse", Kind: "file", Vals: ""},
		{Flag: "--config", Kind: "file", Vals: ""},
		{Flag: "-c", Kind: "file", Vals: ""},
		{Flag: "--enable", Kind: "file", Vals: ""},
		{Flag: "--disable", Kind: "file", Vals: ""},
	}},
	{Fn: "codex__plugin__marketplace__help", Opts: "add list upgrade remove help", Level: 4},
	{Fn: "codex__plugin__marketplace__help__add", Opts: "", Level: 5},
	{Fn: "codex__plugin__marketplace__help__help", Opts: "", Level: 5},
	{Fn: "codex__plugin__marketplace__help__list", Opts: "", Level: 5},
	{Fn: "codex__plugin__marketplace__help__remove", Opts: "", Level: 5},
	{Fn: "codex__plugin__marketplace__help__upgrade", Opts: "", Level: 5},
	{Fn: "codex__plugin__marketplace__list", Opts: "-c -h --config --enable --disable --help", Level: 4, Flags: []bashFlagDetail{
		{Flag: "--config", Kind: "file", Vals: ""},
		{Flag: "-c", Kind: "file", Vals: ""},
		{Flag: "--enable", Kind: "file", Vals: ""},
		{Flag: "--disable", Kind: "file", Vals: ""},
	}},
	{Fn: "codex__plugin__marketplace__remove", Opts: "-c -h --config --enable --disable --help <MARKETPLACE_NAME>", Level: 4, Flags: []bashFlagDetail{
		{Flag: "--config", Kind: "file", Vals: ""},
		{Flag: "-c", Kind: "file", Vals: ""},
		{Flag: "--enable", Kind: "file", Vals: ""},
		{Flag: "--disable", Kind: "file", Vals: ""},
	}},
	{Fn: "codex__plugin__marketplace__upgrade", Opts: "-c -h --config --enable --disable --help [MARKETPLACE_NAME]", Level: 4, Flags: []bashFlagDetail{
		{Flag: "--config", Kind: "file", Vals: ""},
		{Flag: "-c", Kind: "file", Vals: ""},
		{Flag: "--enable", Kind: "file", Vals: ""},
		{Flag: "--disable", Kind: "file", Vals: ""},
	}},
	{Fn: "codex__plugin__remove", Opts: "-m -c -h --marketplace --config --enable --disable --help <PLUGIN[@MARKETPLACE]>", Level: 3, Flags: []bashFlagDetail{
		{Flag: "--marketplace", Kind: "file", Vals: ""},
		{Flag: "-m", Kind: "file", Vals: ""},
		{Flag: "--config", Kind: "file", Vals: ""},
		{Flag: "-c", Kind: "file", Vals: ""},
		{Flag: "--enable", Kind: "file", Vals: ""},
		{Flag: "--disable", Kind: "file", Vals: ""},
	}},
	{Fn: "codex__remote__control", Opts: "-c -h --json --config --enable --disable --help start stop help", Level: 2, Flags: []bashFlagDetail{
		{Flag: "--config", Kind: "file", Vals: ""},
		{Flag: "-c", Kind: "file", Vals: ""},
		{Flag: "--enable", Kind: "file", Vals: ""},
		{Flag: "--disable", Kind: "file", Vals: ""},
	}},
	{Fn: "codex__remote__control__help", Opts: "start stop help", Level: 3},
	{Fn: "codex__remote__control__help__help", Opts: "", Level: 4},
	{Fn: "codex__remote__control__help__start", Opts: "", Level: 4},
	{Fn: "codex__remote__control__help__stop", Opts: "", Level: 4},
	{Fn: "codex__remote__control__start", Opts: "-c -h --json --config --enable --disable --help", Level: 3, Flags: []bashFlagDetail{
		{Flag: "--config", Kind: "file", Vals: ""},
		{Flag: "-c", Kind: "file", Vals: ""},
		{Flag: "--enable", Kind: "file", Vals: ""},
		{Flag: "--disable", Kind: "file", Vals: ""},
	}},
	{Fn: "codex__remote__control__stop", Opts: "-c -h --json --config --enable --disable --help", Level: 3, Flags: []bashFlagDetail{
		{Flag: "--config", Kind: "file", Vals: ""},
		{Flag: "-c", Kind: "file", Vals: ""},
		{Flag: "--enable", Kind: "file", Vals: ""},
		{Flag: "--disable", Kind: "file", Vals: ""},
	}},
	{Fn: "codex__responses__api__proxy", Opts: "-c -h --port --server-info --http-shutdown --upstream-url --dump-dir --config --enable --disable --help", Level: 2, Flags: []bashFlagDetail{
		{Flag: "--port", Kind: "file", Vals: ""},
		{Flag: "--server-info", Kind: "file", Vals: ""},
		{Flag: "--upstream-url", Kind: "file", Vals: ""},
		{Flag: "--dump-dir", Kind: "file", Vals: ""},
		{Flag: "--config", Kind: "file", Vals: ""},
		{Flag: "-c", Kind: "file", Vals: ""},
		{Flag: "--enable", Kind: "file", Vals: ""},
		{Flag: "--disable", Kind: "file", Vals: ""},
	}},
	{Fn: "codex__resume", Opts: "-i -m -p -s -C -a -c -h -V --last --all --include-non-interactive --remote --remote-auth-token-env --strict-config --image --model --oss --local-provider --profile --sandbox --dangerously-bypass-hook-trust --cd --add-dir --dangerously-bypass-approvals-and-sandbox --ask-for-approval --search --no-alt-screen --config --enable --disable --help --version [SESSION_ID] [PROMPT]", Level: 2, Flags: []bashFlagDetail{
		{Flag: "--remote", Kind: "file", Vals: ""},
		{Flag: "--remote-auth-token-env", Kind: "file", Vals: ""},
		{Flag: "--image", Kind: "file", Vals: ""},
		{Flag: "-i", Kind: "file", Vals: ""},
		{Flag: "--model", Kind: "file", Vals: ""},
		{Flag: "-m", Kind: "file", Vals: ""},
		{Flag: "--local-provider", Kind: "file", Vals: ""},
		{Flag: "--profile", Kind: "file", Vals: ""},
		{Flag: "-p", Kind: "file", Vals: ""},
		{Flag: "--sandbox", Kind: "vals", Vals: "read-only workspace-write danger-full-access"},
		{Flag: "-s", Kind: "vals", Vals: "read-only workspace-write danger-full-access"},
		{Flag: "--cd", Kind: "file", Vals: ""},
		{Flag: "-C", Kind: "file", Vals: ""},
		{Flag: "--add-dir", Kind: "dir", Vals: ""},
		{Flag: "--ask-for-approval", Kind: "vals", Vals: "untrusted on-failure on-request never"},
		{Flag: "-a", Kind: "vals", Vals: "untrusted on-failure on-request never"},
		{Flag: "--config", Kind: "file", Vals: ""},
		{Flag: "-c", Kind: "file", Vals: ""},
		{Flag: "--enable", Kind: "file", Vals: ""},
		{Flag: "--disable", Kind: "file", Vals: ""},
	}},
	{Fn: "codex__review", Opts: "-c -h --strict-config --uncommitted --base --commit --title --config --enable --disable --help [PROMPT]", Level: 2, Flags: []bashFlagDetail{
		{Flag: "--base", Kind: "file", Vals: ""},
		{Flag: "--commit", Kind: "file", Vals: ""},
		{Flag: "--title", Kind: "file", Vals: ""},
		{Flag: "--config", Kind: "file", Vals: ""},
		{Flag: "-c", Kind: "file", Vals: ""},
		{Flag: "--enable", Kind: "file", Vals: ""},
		{Flag: "--disable", Kind: "file", Vals: ""},
	}},
	{Fn: "codex__sandbox", Opts: "-p -C -c -h --permissions-profile --profile --cd --include-managed-config --allow-unix-socket --log-denials --config --enable --disable --help [COMMAND]...", Level: 2, Flags: []bashFlagDetail{
		{Flag: "--permissions-profile", Kind: "file", Vals: ""},
		{Flag: "--profile", Kind: "file", Vals: ""},
		{Flag: "-p", Kind: "file", Vals: ""},
		{Flag: "--cd", Kind: "file", Vals: ""},
		{Flag: "-C", Kind: "file", Vals: ""},
		{Flag: "--allow-unix-socket", Kind: "file", Vals: ""},
		{Flag: "--config", Kind: "file", Vals: ""},
		{Flag: "-c", Kind: "file", Vals: ""},
		{Flag: "--enable", Kind: "file", Vals: ""},
		{Flag: "--disable", Kind: "file", Vals: ""},
	}},
	{Fn: "codex__stdio__to__uds", Opts: "-c -h --config --enable --disable --help <SOCKET_PATH>", Level: 2, Flags: []bashFlagDetail{
		{Flag: "--config", Kind: "file", Vals: ""},
		{Flag: "-c", Kind: "file", Vals: ""},
		{Flag: "--enable", Kind: "file", Vals: ""},
		{Flag: "--disable", Kind: "file", Vals: ""},
	}},
	{Fn: "codex__unarchive", Opts: "-i -m -p -s -C -c -h --remote --remote-auth-token-env --image --model --oss --local-provider --profile --sandbox --dangerously-bypass-approvals-and-sandbox --dangerously-bypass-hook-trust --cd --add-dir --strict-config --config --enable --disable --help <SESSION>", Level: 2, Flags: []bashFlagDetail{
		{Flag: "--remote", Kind: "file", Vals: ""},
		{Flag: "--remote-auth-token-env", Kind: "file", Vals: ""},
		{Flag: "--image", Kind: "file", Vals: ""},
		{Flag: "-i", Kind: "file", Vals: ""},
		{Flag: "--model", Kind: "file", Vals: ""},
		{Flag: "-m", Kind: "file", Vals: ""},
		{Flag: "--local-provider", Kind: "file", Vals: ""},
		{Flag: "--profile", Kind: "file", Vals: ""},
		{Flag: "-p", Kind: "file", Vals: ""},
		{Flag: "--sandbox", Kind: "vals", Vals: "read-only workspace-write danger-full-access"},
		{Flag: "-s", Kind: "vals", Vals: "read-only workspace-write danger-full-access"},
		{Flag: "--cd", Kind: "file", Vals: ""},
		{Flag: "-C", Kind: "file", Vals: ""},
		{Flag: "--add-dir", Kind: "dir", Vals: ""},
		{Flag: "--config", Kind: "file", Vals: ""},
		{Flag: "-c", Kind: "file", Vals: ""},
		{Flag: "--enable", Kind: "file", Vals: ""},
		{Flag: "--disable", Kind: "file", Vals: ""},
	}},
	{Fn: "codex__update", Opts: "-c -h --config --enable --disable --help", Level: 2, Flags: []bashFlagDetail{
		{Flag: "--config", Kind: "file", Vals: ""},
		{Flag: "-c", Kind: "file", Vals: ""},
		{Flag: "--enable", Kind: "file", Vals: ""},
		{Flag: "--disable", Kind: "file", Vals: ""},
	}},
}
